Repository openshift/osde2e, pull requests merged in 2019-10, with the labels that each got.

#111 Add dryrun option. Fix SDAR-41. Begin version logic refactor.
  Makefile
  docs/Options.md
  e2e.go
  pkg/config/config.go
  pkg/upgrade/releases.go
  version.go
Labels: size/M

#112 Resolve SDAR-44 - only use an enabled version
  pkg/osd/versions.go
Labels: lgtm, size/XS

#113 Add golint-ci to PR check, and make docker image smaller
  .golang-ci.yml
  Dockerfile
  Makefile
  ci/pr_check.sh
  docs/Options.md
  e2e.go
  pkg/config/config.go
  pkg/osd/logs.go
  pkg/osd/quota.go
  pkg/runner/service_test.go
  pkg/testgrid/junit_test.go
  pkg/testgrid/testgrid.go
  pkg/upgrade/releases.go
  setup.go
  test/operators/dedicatedadmin.go
  version.go
Labels: lgtm, size/L

#116 SDAR-51 - Don't send verbose version to upgrade
  pkg/upgrade/upgrade.go
Labels: lgtm, size/XS

#114 SDAR-46 - Bump upgrade acknowledgement timeout to 5min
  Makefile
  pkg/upgrade/upgrade.go
  setup.go
Labels: lgtm, size/XS

#115 SDAR-50. Use Cincinnati for source Openshift version for integration.
  docs/Options.md
  pkg/config/config.go
  pkg/upgrade/releases.go
  version.go
Labels: size/M

#119 Set continer engine in Makefile via environment variable
  Makefile
Labels: lgtm, size/S

#120 SDAR-53 (partial fix) - use wait.PollImmediate and have a timeout
  pkg/runner/pod.go
  pkg/runner/service.go
Labels: lgtm, size/S

#110 configure-alertmanager-operator test & refactor
  test/operators/configurealertmanager.go
  test/operators/dedicatedadmin.go
  test/operators/operators.go
Labels: size/XL

#121 Revert "configure-alertmanager-operator test & refactor"
  test/operators/configurealertmanager.go
  test/operators/dedicatedadmin.go
  test/operators/operators.go
Labels: lgtm, size/XL

#122 SDAR-55: Change minutes to seconds, add some comments
  test/operators/dedicatedadmin.go
Labels: lgtm, size/S

#123 SDAR-53 - Bump cooldown to 10min
  setup.go
Labels: lgtm, size/XS

#124 SDAR-33. Add prow test runners.
  ci/prow_pr_check.sh
  ci/prow_run_tests.sh
Labels: lgtm, size/M

#125 Refactor Operator Test Scaffold; add basic tests
  test/operators/configurealertmanager.go
  test/operators/dedicatedadmin.go
  test/operators/managedvelero.go
  test/operators/operators.go
Labels: lgtm, size/XL

#127 SDAR-60 - Fix operator timeouts
  test/operators/operators.go
Labels: lgtm, size/XS

#130 SDCICD-40. Use MAJOR_TARGET and MINOR_TARGET to target CIS versions.
  pkg/osd/versions.go
  version.go
Labels: approved, size/S

#131 SDCICD-40. Use OCM directly for int versions.
  pkg/osd/versions.go
Labels: approved, lgtm, size/S

#132 SDCICD-58. Recognize paginated results from cluster versions endpoint.
  pkg/osd/versions.go
Labels: approved, lgtm, size/M

#133 SDCICD-59. Propagate timeout to waitForEndpoints.
  pkg/runner/git_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/service.go
  pkg/runner/service_test.go
  test/openshift/openshift.go
  test/state/mustgather.go
  test/state/prometheus.go
Labels: approved, lgtm, size/M

#134 SDCICD-62. Pipe output to REPORT_DIR as part of prow scripts
  ci/prow_pr_check.sh
  ci/prow_run_tests.sh
Labels: approved, lgtm, size/M

#135 Use cvo and osd-verify checks to determine cluster health
  pkg/helper/nodes.go
  pkg/helper/operators.go
  pkg/helper/pods.go
  pkg/osd/cluster.go
  setup.go
Labels: approved, lgtm, size/L

#138 SDICD-48 - Use CVO / Cluster State to determine when to start tests
  pkg/helper/clusterversionoperator.go
  pkg/helper/clusterversionoperator_test.go
  pkg/helper/nodes.go
  pkg/helper/nodes_test.go
  pkg/helper/operators.go
  pkg/helper/operators_test.go
  pkg/helper/pods.go
  pkg/helper/pods_test.go
  pkg/osd/cluster.go
  setup.go
Labels: approved, lgtm, size/XL

#139 Fix typo, add one more operator test
  pkg/helper/clusterversionoperator.go
  pkg/helper/clusterversionoperator_test.go
  pkg/helper/operators.go
Labels: approved, size/S

#140 Fix another failed condition
  pkg/helper/clusterversionoperator.go
  pkg/helper/clusterversionoperator_test.go
Labels: approved, size/XS

#141 SDCICD-65 - Fix behavior with a provided Kubeconfig
  e2e.go
  setup.go
Labels: approved, lgtm, size/M

#136 SDCICD-35. Excise TestGrid publishing.
  Dockerfile
  Makefile
  README.md
  ci/prow_pr_check.sh
  ci/prow_run_tests.sh
  cmd/osde2e-docs/main.go
  cmd/osde2e-report/main.go
  docs/Options.md
  docs/Writing-Tests.md
  e2e.go
  glide.lock
  glide.yaml
  pkg/config/config.go
  pkg/config/testgrid.go
  pkg/report/config.go
  pkg/report/markdown.go
  pkg/report/markdown_test.go
  pkg/report/report.go
  pkg/report/runs.go
  pkg/testgrid/artifacts.go
  pkg/testgrid/builds.go
  pkg/testgrid/junit.go
  pkg/testgrid/junit_test.go
  pkg/testgrid/latest.go
  pkg/testgrid/testgrid.go
  pkg/testgrid/testgrid_test.go
Labels: approved, lgtm, size/XXL

#142 Allow polling timeout to be configurable
  cmd/osde2e-docs/Options.md.tmpl
  cmd/osde2e-docs/docs.go
  cmd/osde2e-docs/parse.go
  docs/Options.md
  pkg/config/config.go
  pkg/config/load.go
  test/operators/dedicatedadmin.go
  test/operators/operators.go
Labels: approved, lgtm, size/M

#137 SDCICD-43. Excise TARGET_STREAM.
  Makefile
  docs/Options.md
  pkg/config/config.go
  version.go
Labels: approved, lgtm, size/S

#145 CICD-69 - Output more pod info
  pkg/helper/pods.go
  pkg/helper/pods_test.go
Labels: approved, lgtm, size/XS

#144 CICD-71 - Set default values in config file.
  docs/Options.md
  e2e.go
  pkg/config/config.go
  pkg/osd/cluster.go
  setup.go
  version.go
Labels: approved, lgtm, size/M

#146 CICD-73 - Fix bool default logic
  pkg/config/load.go
Labels: approved, size/XS

#147 CICD-73 - Better bool logic
  pkg/config/load.go
Labels: approved, lgtm, size/XS
