Repository openshift/osde2e, pull requests merged in 2019-09, with the labels that each got.

#88 SDAR-22. Modify stage and prod to use Cincinnati.
  pkg/osd/versions.go
  pkg/upgrade/releases.go
  pkg/upgrade/upgrade.go
  version.go
Labels: lgtm, size/L

#89 adding clusterRoleBinding tests; formatting
  test/operators/dedicatedadmin.go
Labels: size/M

#91 renamed main tests to better label responsible group
  test/operators/dedicatedadmin.go
Labels: lgtm, size/S

#92 Increase olm grace period
  test/operators/dedicatedadmin.go
Labels: lgtm, size/S

#93 Allow Makefile to pass CLUSTER_VERSION env variable to Docker container
  Makefile
Labels: lgtm, size/XS

#94 ignore VSCode workspace and vi/vim swp files
  .gitignore
Labels: lgtm, size/XS

#95 SDAR-30. Remove CLEAN_RUNS from upgrade tests.
  ci/upgrade_events.sh
Labels: lgtm, size/XS

#96 SDAR-31. Add an hour wait after test completion.
  pkg/config/config.go
  setup.go
Labels: size/S

#97 SDAR-31. Increase test.timeout to 4h.
  Makefile
  README.md
Labels: size/XS

#99 adding operator-lifecycle-manager clientsets
  glide.lock
  glide.yaml
  pkg/helper/clientsets.go
Labels: size/M

#98 Remove operator testing, make debug sleep optional
  Makefile
  docs/Options.md
  e2e_test.go
  pkg/config/config.go
  setup.go
Labels: lgtm, size/M

#100 Cross-stream support, Dedicated Admin Operator timeout changes
  Makefile
  docs/Options.md
  pkg/config/config.go
  pkg/upgrade/releases.go
  test/openshift/openshift.go
  test/operators/dedicatedadmin.go
  test/state/mustgather.go
  test/state/prometheus.go
  test/state/state.go
  test/verify/imagestreams.go
  test/verify/pods.go
  test/verify/projects.go
  test/verify/routes.go
  version.go
Labels: size/L

#102 fixing syntax error in version.go
  version.go
Labels: size/XS

#103 SDAR-36. Use DefaultVersion instead of PreviousVersion for upgrades.
  version.go
Labels: lgtm, size/XS

#104 Cluster service version
  test/operators/dedicatedadmin.go
Labels: lgtm, size/L

#101 Adding in OWNERS file.
  OWNERS
Labels: lgtm, size/S

#105 Fix condition where targetstream would not be honored
  version.go
Labels: lgtm, size/S

#106 SDAR-34. Fail when no quota is available.
  e2e.go
Labels: lgtm, size/XS

#108 Wrap ginkgo skip in quotes
  Makefile
Labels: size/XS

#109 if upgrade and target are the same, look for the previous version
  version.go
Labels: lgtm, size/XS

#107 Look for version prefix expected by cluster
  pkg/upgrade/releases.go
  setup.go
  version.go
Labels: lgtm, size/M
