Repository openshift/osde2e, pull requests merged in 2019-06, with the labels that each got.

#28 Use latest available rc by default
  Makefile
  pkg/osd/versions.go
  setup.go
Labels: size/S

#30 Enable OSD debug logs
  Makefile
  glide.lock
  glide.yaml
Labels: size/XS

#33 Report cluster state as part of artifacts
  e2e_test.go
  pkg/helper/clientsets.go
  pkg/helper/state.go
  pkg/testgrid/builds.go
  test/state/state.go
Labels: size/L

#36 Run must-gather
  pkg/helper/runner.go
  pkg/runner/command.go
  pkg/runner/runner.go
  test/openshift/config.go
  test/openshift/openshift.go
  test/state/mustgather.go
Labels: size/L

#38 Rename must-gather output
  pkg/runner/command.go
  pkg/runner/pod.go
  pkg/runner/runner.go
  test/state/mustgather.go
Labels: size/S

#40 Use default version from OSD for clusters
  glide.lock
  glide.yaml
  pkg/osd/osd.go
  pkg/osd/versions.go
  setup.go
Labels: size/M

#43 remove docker containers after use
  Makefile
Labels: lgtm, size/XS

#44 Bump uhc-sdk-go to v0.1.23
  README.md
  glide.lock
  glide.yaml
Labels: size/S

#46 Collect prometheus data
  test/state/prometheus.go
Labels: size/M
