Repository openshift/osde2e, pull requests merged in 2019-11, with the labels that each got.

#148 SDCICD-27. Make cluster expiry configurable and update to ocm-go-sdk.
  docs/Options.md
  docs/Writing-Tests.md
  glide.lock
  glide.yaml
  pkg/config/config.go
  pkg/osd/cluster.go
  pkg/osd/logs.go
  pkg/osd/osd.go
  pkg/osd/quota.go
  pkg/osd/versions.go
  setup.go
Labels: approved, lgtm, size/L

#149 CICD-78: Add config option to skip certain operator health checks
  docs/Options.md
  pkg/config/config.go
  pkg/helper/operators.go
  pkg/helper/operators_test.go
  pkg/osd/cluster.go
Labels: approved, lgtm, size/M

#150 SDCICD-76: Check cluster readiness post-upgrade, not just pre
  pkg/upgrade/upgrade.go
  setup.go
Labels: approved, lgtm, size/S

#151 SDCICD-81. Config loader now handles 'false' bool values.
  pkg/config/load.go
Labels: approved, lgtm, size/S

#143 SDCICD-63. Reintroduce NodeVertical tests.
  Makefile
  ci/prow_pr_check.sh
  common/e2e.go
  common/setup.go
  common/version.go
  pkg/runner/runner.go
  pkg/runner/service.go
  pkg/runner/service_test.go
  suites/e2e/e2e_test.go
  suites/scale/scale_test.go
  test/scale/nodevertical.go
  test/scale/scale.go
Labels: approved, lgtm, size/L

#153 SDCICD-63. Update prow run script to run different test suites.
  ci/prow_run_tests.sh
Labels: approved, lgtm, size/S

#154 CICD-6: Run tests pre and post upgrade
  common/e2e.go
  common/setup.go
  pkg/helper/helper.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#152 SDCICD-50: Create example for test workloads
  .golang-ci.yml
  Dockerfile
  Makefile
  artifacts/.DS_Store
  artifacts/workloads/e2e/guestbook/frontend-deployment.yaml
  artifacts/workloads/e2e/guestbook/frontend-service.yaml
  artifacts/workloads/e2e/guestbook/redis-master-deployment.yaml
  artifacts/workloads/e2e/guestbook/redis-master-service.yaml
  artifacts/workloads/e2e/guestbook/redis-slave-deployment.yaml
  artifacts/workloads/e2e/guestbook/redis-slave-service.yaml
  artifacts/workloads/tests/badpod.yaml
  artifacts/workloads/tests/pod.yaml
  artifacts/workloads/tests/pods.yaml
  artifacts/workloads/tests/service.yaml
  pkg/helper/helper.go
  pkg/helper/workloads.go
  pkg/helper/workloads_test.go
  suites/e2e/e2e_test.go
  test/workloads/guestbook/guestbook.go
Labels: approved, lgtm, size/L

#155 SDCICD-50: Fix filewalk bug
  pkg/helper/workloads.go
Labels: approved, lgtm, size/XS

#156 SDCICD-50: Change filepath for artifacts
  test/workloads/guestbook/guestbook.go
Labels: approved, lgtm, size/XS

#157 SDCICD-91. Collect metadata and report it during a run.
  common/e2e.go
  common/setup.go
  common/version.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  pkg/osd/cluster.go
Labels: approved, lgtm, size/L

#158 SDCICD-98. Rename UHC_TOKEN to OCM_TOKEN.
  ci/prow_run_tests.sh
  common/e2e.go
  docs/Options.md
  pkg/config/config.go
Labels: approved, lgtm, size/S

#159 SDCICD-72: Fail osde2e fast if it encounters errors
  common/e2e.go
  pkg/helper/pods.go
  pkg/helper/pods_test.go
  pkg/osd/cluster.go
Labels: approved, lgtm, size/M

#162 Fix prometheus gather flake
  test/state/prometheus.go
Labels: approved, lgtm, size/XS
