Repository openshift/osde2e, pull requests merged in 2019-12, with the labels that each got.

#161 Add ginkgo.focus option
  Makefile
  docs/Options.md
  pkg/config/config.go
Labels: approved, lgtm, size/S

#163 SDCICD-92 - Re-enable post-upgrade workload tests
  common/e2e.go
  pkg/config/config.go
  pkg/helper/helper.go
  test/workloads/guestbook/guestbook.go
Labels: approved, lgtm, size/M

#165 Add e2e tests for operator curator
  test/operators/curator.go
Labels: approved, lgtm, size/M

#160 Add e2e test for certman
  test/operators/certman.go
Labels: approved, lgtm, size/M

#167 Update certman tests
  test/operators/certman.go
Labels: approved, lgtm, size/S

#168 SDCICD-101. Get cluster name for existing clusters.
  common/setup.go
Labels: approved, lgtm, size/S

#170 Replace missed references to UHC with OCM.
  Makefile
  README.md
  common/setup.go
Labels: approved, lgtm, size/XS

#164 SDCICD-56: Migrate to go modules
  Dockerfile
  Makefile
  README.md
  ci/prow_setup.sh
  glide.lock
  glide.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#172 SDCICD-95. Preliminary metrics-sync.sh script.
  scripts/README.md
  scripts/metrics-sync.sh
Labels: approved, lgtm, size/M

#171 Add tests for osd prune jobs
  test/operators/prunejob.go
Labels: approved, lgtm, size/M

#174 SDCICD-103. Fix panic in certman test.
  test/operators/certman.go
Labels: approved, lgtm, size/XS

#166 SDCICD-54. Metrics are now exported in prometheus exposition format.
  common/e2e.go
  common/metrics.go
  common/metrics_test.go
  docs/Options.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/helper/runner.go
Labels: approved, lgtm, size/XL

#175 SDCICD-54. Upload metrics to S3 bucket.
  ci/prow_run_tests.sh
  cmd/osde2e-docs/main.go
  common/e2e.go
  docs/Options.md
  go.mod
  go.sum
  pkg/config/config.go
  scripts/README.md
  scripts/metrics-sync.sh
Labels: approved, lgtm, size/L

#178 SDCICD-54. Fix another typo in the run tests script.
  ci/prow_run_tests.sh
Labels: approved, lgtm, size/XS

#176 SDCICD-83 - Support job configuration by optional YAML file
  Makefile
  common/e2e.go
  common/metrics.go
  common/metrics_test.go
  common/setup.go
  common/version.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/load.go
  pkg/helper/helper.go
  pkg/helper/operators.go
  pkg/helper/operators_test.go
  pkg/osd/cluster.go
  pkg/osd/quota.go
  pkg/osd/versions.go
  pkg/upgrade/releases.go
  pkg/upgrade/upgrade.go
  suites/e2e/e2e_test.go
  suites/scale/scale_test.go
  test/operators/certman.go
  test/operators/curator.go
  test/operators/dedicatedadmin.go
  test/operators/operators.go
  test/operators/prunejob.go
Labels: approved, lgtm, size/XL

#179 SDCICD-105. Disable dedicated admin operator tests.
  test/operators/dedicatedadmin.go
Labels: approved, lgtm, size/XS

#180 SDCICD-83 - Remove artifact from earlier attempt
  suites/e2e/e2e_test.go
  suites/scale/scale_test.go
  test/operators/operators.go
Labels: approved, lgtm, size/S

#181 SDCICD-83 - Bug fix
  pkg/config/load.go
Labels: approved, lgtm, size/XS

#182 Strip trailing slashes from the push gateway in the metrics-sync script.
  scripts/metrics-sync.sh
Labels: approved, lgtm, size/XS

#183 SDCICD-87. Addon test harness support.
  .gitignore
  Makefile
  cmd/osde2e-docs/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/helper/helper.go
  pkg/helper/runner.go
  pkg/osd/cluster.go
  pkg/runner/command.go
  pkg/runner/imagestream.go
  pkg/runner/imagestream_test.go
  pkg/runner/pod.go
  pkg/runner/runner.go
  suites/addons/addons_test.go
  suites/addons/testdata/addon-runner.template
  test/addons/addon_test_harness.go
  test/openshift/openshift.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#184 SDCICD-87. Fix command rework bug for single line commands.
  pkg/runner/command.go
Labels: approved, lgtm, size/XS

#186 SDCICD-87. Make sure runners run as root.
  pkg/runner/pod.go
Labels: approved, lgtm, size/XS

#188 SDCICD-111: Fail test run if upgrade times out
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/S

#187 SDCICD-108. Counter event support.
  common/e2e.go
  common/e2e_test.go
  common/metrics.go
  common/setup.go
  pkg/events/event_type.go
  pkg/events/events.go
  pkg/events/events_test.go
Labels: approved, lgtm, size/L

#189 SDCICD-114. Use osd-4 for default flavor for new clusters.
  pkg/osd/cluster.go
Labels: approved, lgtm, size/XS

#190 SDCICD-113. Get Hive logs after each test.
  common/setup.go
Labels: approved, lgtm, size/S

#191 Update Options.md
  docs/Options.md
  pkg/config/config.go
Labels: approved, lgtm, size/XS

#192 Add tests to ensure certain pods appear on infra nodes
  test/verify/infranodes.go
Labels: approved, lgtm, size/M

#193 SDCICD-115. Support multiple secrets locations, addon secrets.
  ci/prow_pr_check.sh
  ci/prow_run_tests.sh
  ci/prow_setup.sh
Labels: approved, lgtm, size/M

#194 SDCICD-112 - Update README and Makefile
  Makefile
  README.md
Labels: approved, lgtm, size/L

#195 SDCICD-89. General fixes for addon support.
  pkg/osd/cluster.go
  pkg/osd/osd.go
  suites/addons/addons_test.go
Labels: approved, lgtm, size/M
