Repository openshift/osde2e, pull requests merged in 2019-07, with the labels that each got.

#47 Extend Go test timeout to 3hr
  Makefile
Labels: size/XS

#49 Upgrades
  pkg/config/config.go
  pkg/helper/clientsets.go
  pkg/osd/versions.go
  pkg/runner/command.go
  pkg/upgrade/releases.go
  pkg/upgrade/upgrade.go
  setup.go
  version.go
Labels: size/L

#50 Remove old ci script symlinks
  build_deploy.sh
  pr_check.sh
  run_tests.sh
Labels: size/XS

#55 Set cluster expiration timestamp
  pkg/osd/cluster.go
Labels: size/XS

#57 Infra for scale runner
  pkg/runner/command.go
  pkg/runner/git.go
  pkg/runner/pod.go
  pkg/runner/runner.go
  test/scale/nodevertical.go
  test/scale/scale.go
Labels: size/L

#59 Require at least 3 CLEAN_RUNS, remove NEW_ONLY
  ci/upgrade_events.sh
  e2e.go
  pkg/config/config.go
  pkg/config/load.go
  pkg/testgrid/latest.go
  pkg/testgrid/testgrid_test.go
Labels: size/M

#60 Support retrieving JUnit results for a build
  pkg/testgrid/builds.go
  pkg/testgrid/junit.go
  pkg/testgrid/junit_test.go
  pkg/testgrid/testgrid_test.go
Labels: size/L

#67 Fix race condition with service account
  pkg/runner/pod.go
Labels: size/S

#68 Support for cloning Git repos using Runner
  pkg/runner/git.go
  pkg/runner/git_test.go
  pkg/runner/pod.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/service.go
Labels: size/L
