Repository openshift/osde2e, pull requests merged in 2020-03, with the labels that each got.

#253 SDCICD-20. Fix failing scale tests.
  pkg/common/config/config.go
  pkg/e2e/scale/scale.go
Labels: approved, lgtm, size/S

#255 Hopefully fix pbench secrets.
  ci/prow_run_tests.sh
Labels: approved, lgtm, size/XS

#252 Added tests for the OSD Managed Cluster Validation Webhook
  pkg/e2e/verify/validation_webhook.go
Labels: approved, lgtm, size/M

#257 SDCICD-173. Gate report script.
  scripts/gate-report.sh
  scripts/metrics-sync.sh
Labels: approved, size/M

#258 SDCICD-173. Add environment to report filename.
  scripts/gate-report.sh
Labels: approved, size/XS

#259 SDCICD-173. Bugfixes for the gate-report.sh script.
  scripts/gate-report.sh
Labels: approved, size/XS

#261 Fix addon tests.
  ci/prow_run_tests.sh
Labels: approved, size/XS

#262 SDCICD-173. Fix gate command.
  scripts/gate-report.sh
Labels: approved, size/XS

#264 SDCICD-173. Use docker image for gate report generation.
  scripts/gate-report.sh
Labels: approved, size/XS

#256 Update tests for dedicated-admin with RBAC operator
  pkg/e2e/operators/dedicatedadmin.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/rbac.go
Labels: approved, lgtm, size/L

#263 SDCICD-194. Exit gracefully for middle/oldest imageset tests.
  pkg/common/osd/versions.go
  pkg/common/state/state.go
  pkg/e2e/e2e.go
  pkg/e2e/version.go
Labels: approved, lgtm, size/M

#265 SDCICD-195. Fail if no versions can be found for gate report.
  pkg/gate/generate_report.go
Labels: approved, lgtm, size/S

#266 SDCICD-174. Scripts should always grab the most recent image.
  scripts/gate-report-analysis.sh
  scripts/gate-report.sh
Labels: approved, lgtm, size/XS

#267 SDCICD-174. Use AWS CLI docker container.
  scripts/gate-report-analysis.sh
  scripts/gate-report.sh
Labels: approved, lgtm, size/S

#269 SDCICD-174. Add in missing $AWS substitution.
  scripts/gate-report-analysis.sh
Labels: approved, lgtm, size/XS

#268 Add tests for splunk-forwarder-operator
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm, size/M

#272 Added tests for SRE Prometheus exporters
  pkg/e2e/verify/prom_exporters.go
Labels: approved, lgtm, size/M

#273 SDCICD-203. Always use fast-x.y channel when attempting upgrades via …
  pkg/common/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#274 SDCICD-204. Use candidate-x.y channel for rcs.
  pkg/common/upgrade/upgrade.go
Labels: approved, lgtm

#275 SDCICD-206. Filter upgrade version CISes if they're not in Cincinnati.
  pkg/common/osd/versions.go
  pkg/common/upgrade/releases.go
  pkg/common/upgrade/upgrade.go
  pkg/e2e/version.go
Labels: approved, lgtm

#276 SDCICD-205. Adjust metrics sync expirations
  scripts/metrics-sync.sh
Labels: approved, lgtm

#278 Revert "Merge pull request #276 from meowfaceman/SDCICD-205"
  scripts/metrics-sync.sh
Labels: approved

#270 SDCICD-152: Pass the build number and cluster id to prom metadata
  docs/Addons.md
  docs/Options.md
  pkg/common/config/config.go
  pkg/e2e/metrics.go
  pkg/e2e/metrics_test.go
Labels: approved, lgtm, size/M

#277 SDCICD-186: Test privileged container permissions
  cmd/osde2e/test/test.go
  configs/e2e-suite.yaml
  pkg/common/helper/clientsets.go
  pkg/common/helper/helper.go
  pkg/common/helper/projects.go
  pkg/common/load/load.go
  pkg/common/runner/git_test.go
  pkg/common/runner/runner_test.go
  pkg/common/util/util.go
  pkg/e2e/osd/privileged.go
Labels: approved, lgtm

#280 Introduce shellcheck.
  Makefile
  scripts/.gitignore
  scripts/gate-report-analysis.sh
  scripts/gate-report.sh
  scripts/metrics-sync.sh
  scripts/shellcheck.sh
Labels: approved, lgtm

#282 SDCICD-210. Use fixed operator versions to test upgrades.
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#283 SDCICD-210. Remove checks for the Replaces field.
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#279 SDCICD-205. Correctly add in metrics-sync expiration reduction.
  scripts/metrics-sync.sh
Labels: approved, lgtm

#281 SDCICD-209. Reduce number of samples needed in generate_report.
  pkg/gate/generate_report.go
Labels: approved, lgtm

#285 Revert SDCICD-210 short term fix.
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#284 SDCICD-212. Use AppsV1 instead of ExtensionV1beta1 for daemonset check.
  pkg/common/osd/versions.go
  pkg/e2e/setup.go
  pkg/e2e/verify/prom_exporters.go
  pkg/e2e/version.go
Labels: approved, lgtm

#286 SDCICD-210. Resubmit fixed operator upgrades.
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#288 SDCICD-211. Remove prometheus-exporter-machine-api checks.
  pkg/e2e/verify/prom_exporters.go
Labels: approved, lgtm

#287 SDCICD-210. Remove operator upgrade tests.
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#290 SDCICD-212. Use semver constraint instead of version comparison.
  pkg/common/osd/versions.go
  pkg/common/osd/versions_test.go
  pkg/e2e/verify/prom_exporters.go
Labels: approved, lgtm

#291 Set operator upgrades to automatic after first manual test refs OSD-3141
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#289 OSD-2132 Introducing tests for Customer Perspective Testing
  Makefile
  configs/app-build-suite.yaml
  pkg/e2e/openshift/app_builds.go
  pkg/e2e/openshift/config.go
Labels: approved, lgtm

#292 SDCICD-215. Stick with one test suite for now.
  Makefile
  configs/app-build-suite.yaml
  configs/e2e-suite.yaml
Labels: approved, lgtm

#294 Removing app builds cakephp-mysql and nodejs-mongodb
  pkg/e2e/openshift/app_builds.go
Labels: approved, lgtm

#293 Extend the poll timeout for CSV on operator upgrade checks.
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#295 SDCICD-213, SDCICD-208, SDCICD-216, Others
  configs/e2e-suite.yaml
  configs/run-as-dedicated-admin.yaml
  go.mod
  go.sum
  pkg/common/config/config.go
  pkg/common/helper/helper.go
  pkg/common/helper/projects.go
  pkg/common/osd/cluster.go
  pkg/common/runner/pod.go
  pkg/common/state/state.go
  pkg/common/upgrade/upgrade.go
  pkg/e2e/e2e.go
  pkg/e2e/openshift/conformance.go
  pkg/e2e/openshift/disruptive.go
  pkg/e2e/openshift/images.go
  pkg/e2e/operators/operators.go
  pkg/e2e/osd/privileged.go
  pkg/e2e/verify/storage.go
  pkg/e2e/workloads/guestbook/guestbook.go
Labels: approved, lgtm

#296 Remove openshift-extended tests from default e2e runs
  configs/e2e-suite.yaml
  configs/openshift-suite.yaml
Labels: approved, lgtm

#298 SDCICD-167. Test for critical cluster alerts.
  Dockerfile
  assets/.DS_Store
  assets/addons/addon-runner.template
  assets/scale/scale-runner.template
  assets/state/alerts.template
  assets/workloads/e2e/guestbook/frontend-deployment.yaml
  assets/workloads/e2e/guestbook/frontend-service.yaml
  assets/workloads/e2e/guestbook/redis-master-deployment.yaml
  assets/workloads/e2e/guestbook/redis-master-service.yaml
  assets/workloads/e2e/guestbook/redis-slave-deployment.yaml
  assets/workloads/e2e/guestbook/redis-slave-service.yaml
  assets/workloads/tests/badpod.yaml
  assets/workloads/tests/pod.yaml
  assets/workloads/tests/pods.yaml
  assets/workloads/tests/service.yaml
  go.sum
  pkg/common/helper/workloads_test.go
  pkg/e2e/addons/addon_test_harness.go
  pkg/e2e/scale/scale.go
  pkg/e2e/state/alerts.go
  pkg/e2e/workloads/guestbook/guestbook.go
  pkged.go
Labels: approved, lgtm

#301 Fix ginkgo panic on helper cleanup failure.
  pkg/e2e/e2e.go
Labels: approved, lgtm

#302 Ensure alert scraper test runs as cluster-admin
  pkg/e2e/state/alerts.go
Labels: approved, lgtm

#300 OSD-2132 Add Redmine workload
  assets/workloads/e2e/redmine/mysql-deployment.yaml
  assets/workloads/e2e/redmine/mysql-pvc.yaml
  assets/workloads/e2e/redmine/mysql-root-secret.yaml
  assets/workloads/e2e/redmine/mysql-secret.yaml
  assets/workloads/e2e/redmine/mysql-service.yaml
  assets/workloads/e2e/redmine/redmine-deployment.yaml
  assets/workloads/e2e/redmine/redmine-pvc.yaml
  assets/workloads/e2e/redmine/redmine-service.yaml
  cmd/osde2e/test/test.go
  pkg/common/helper/workloads.go
  pkg/e2e/workloads/redmine/redmine.go
Labels: approved, lgtm

#303 Additional permission fixes for tests
  pkg/common/runner/pod.go
  pkg/e2e/openshift/conformance.go
  pkg/e2e/osd/privileged.go
  pkg/e2e/state/alerts.go
Labels: approved, lgtm

#304 SDCICD-214. Enable dynamic version selection for fresh installs.
  configs/one-release-from-prod-default.yaml
  configs/two-releases-from-prod-default.yaml
  pkg/common/config/config.go
  pkg/common/osd/versions.go
  pkg/common/osd/versions_test.go
  pkg/e2e/version.go
Labels: approved, lgtm

#307 Bugfix: Grant cluster-admin to addon tests
  pkg/e2e/addons/addon_test_harness.go
Labels: approved, lgtm

#308 Bugfix: Scale tests should run as cluster-admin
  pkg/e2e/scale/nodes_and_pods.go
  pkg/e2e/scale/performance.go
  pkg/e2e/scale/scale.go
Labels: approved, lgtm

#306 SDCICD-198 - Create junit.xml based on observed log metrics
  pkg/e2e/e2e.go
Labels: approved, lgtm

#305 SDCICD-214. Enable dynamic version selection for upgrades.
  configs/nightly-release-for-prod-default.yaml
  configs/upgrade-nightly-release-for-prod-default.yaml
  configs/upgrade-one-release-from-prod-default.yaml
  configs/upgrade-two-releases-from-prod-default.yaml
  pkg/common/config/config.go
  pkg/common/osd/versions.go
  pkg/common/upgrade/releases.go
  pkg/e2e/version.go
Labels: approved, lgtm

#309 SDCICD-214. Move quota check.
  pkg/e2e/e2e.go
Labels: approved, lgtm

#310 Fix scale tests.
  assets/scale/scale-runner.template
  pkg/e2e/scale/scale.go
  pkged.go
Labels: approved, lgtm

#313 Fix addon tests.
  assets/addons/addon-runner.template
  pkg/e2e/addons/addon_test_harness.go
Labels: approved, lgtm

#311 CICD-197: Run must gather and collect state info after tests have run
  pkg/common/helper/helper.go
  pkg/e2e/setup.go
  pkg/e2e/state/mustgather.go
  pkg/e2e/state/state.go
Labels: approved, lgtm

#314 Debug: Add info to OCM version query failures
  pkg/common/osd/versions.go
Labels: approved, lgtm
