Repository openshift/osde2e, pull requests merged in 2020-06, with the labels that each got.

#415 SDCICD-327. Check if cluster is null during cluster wait.
  pkg/common/cluster/clusterutil.go
Labels: approved, lgtm

#414 Bumping previousCSV values for operator upgrade tests
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#416 SDCICD-332. Fix must-gather for prow jobs.
  cmd/osde2e/test/cmd.go
Labels: approved, lgtm

#417 SDCICD-331: Fix Viper comparison for Diff generation
  pkg/common/cluster/clusterutil.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#420 SDCICD-297. Alter metrics AWS parsing to support MOA pipelines.
  ci/prow_run_tests.sh
  ci/prow_setup.sh
  pkg/common/aws/s3.go
  pkg/common/aws/session.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#419 SDCICD-293: Add provider metrics and test OCM metrics endpoint
  pkg/common/providers/crc/crc.go
  pkg/common/providers/moaprovider/wrapped_calls.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/ocm.go
  pkg/common/spi/cluster.go
  pkg/common/spi/provider.go
  pkg/e2e/osd/ocm.go
Labels: approved, lgtm

#424 SDCICD-200. Export MOA variables in prow script.
  ci/prow_run_tests.sh
Labels: approved, lgtm

#426 SDCICD-200. Add in ARTIFACTS config.
  pkg/common/config/config.go
  pkg/common/load/load.go
Labels: approved, lgtm

#425 SDCICD-335. Skip curator tests for MOA clusters.
  pkg/e2e/operators/curator.go
Labels: approved, lgtm

#421 OSD-3680 Add route monitoring during upgrades
  go.mod
  go.sum
  pkg/common/config/config.go
  pkg/common/metadata/metadata.go
  pkg/e2e/e2e.go
  pkg/e2e/routemonitors/routemonitors.go
  pkg/e2e/workloads/guestbook/guestbook.go
  pkg/e2e/workloads/redmine/redmine.go
Labels: approved, lgtm

#428 SDCICD-200. Trim leading/trailing whitespace from secrets.
  pkg/common/load/load.go
Labels: approved, lgtm

#429 Update vendor directory.
  vendor/github.com/influxdata/tdigest/.gitignore
  vendor/github.com/influxdata/tdigest/LICENSE
  vendor/github.com/influxdata/tdigest/README.md
  vendor/github.com/influxdata/tdigest/centroid.go
  vendor/github.com/influxdata/tdigest/go.mod
  vendor/github.com/influxdata/tdigest/go.sum
  vendor/github.com/influxdata/tdigest/tdigest.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr.go
  vendor/github.com/mailru/easyjson/jlexer/bytestostr_nounsafe.go
  vendor/github.com/mailru/easyjson/jlexer/error.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/tsenart/go-tsz/.gitignore
  vendor/github.com/tsenart/go-tsz/.travis.yml
  vendor/github.com/tsenart/go-tsz/LICENSE
  vendor/github.com/tsenart/go-tsz/Makefile
  vendor/github.com/tsenart/go-tsz/README.md
  vendor/github.com/tsenart/go-tsz/VERSION
  vendor/github.com/tsenart/go-tsz/bstream.go
  vendor/github.com/tsenart/go-tsz/fuzz.go
  vendor/github.com/tsenart/go-tsz/testdata/data.go
  vendor/github.com/tsenart/go-tsz/tsz.go
  vendor/github.com/tsenart/vegeta/LICENSE
  vendor/github.com/tsenart/vegeta/lib/attack.go
  vendor/github.com/tsenart/vegeta/lib/histogram.go
  vendor/github.com/tsenart/vegeta/lib/lttb/lttb.go
  vendor/github.com/tsenart/vegeta/lib/metrics.go
  vendor/github.com/tsenart/vegeta/lib/pacer.go
  vendor/github.com/tsenart/vegeta/lib/plot/assets.go
  vendor/github.com/tsenart/vegeta/lib/plot/assets_vfsdata.go
  vendor/github.com/tsenart/vegeta/lib/plot/plot.go
  vendor/github.com/tsenart/vegeta/lib/plot/timeseries.go
  vendor/github.com/tsenart/vegeta/lib/reporters.go
  vendor/github.com/tsenart/vegeta/lib/results.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/lib/targets.go
  vendor/github.com/tsenart/vegeta/lib/targets_easyjson.go
  vendor/modules.txt
Labels: approved, lgtm

#427 Safe handling of helper in routemonitor code
  pkg/e2e/routemonitors/routemonitors.go
Labels: approved, lgtm

#423 SDCICD-294: Define per-ginkgo-context alerting mechanism
  cmd/osde2e/alert/cmd.go
  cmd/osde2e/main.go
  go.mod
  go.sum
  pkg/common/alert/alert.go
  pkg/common/config/config.go
  pkg/common/prometheus/connect.go
  pkg/e2e/osd/daemonsets.go
Labels: approved, lgtm

#431 SDCICD-183: Support cluster creation with custom compute machine types
  configs/ocm-aws-compute-optimized.yaml
  configs/ocm-aws-memory-optimized.yaml
  configs/ocm-gcp-compute-optimized.yaml
  configs/ocm-gcp-memory-optimized.yaml
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
Labels: approved, lgtm

#430 SDCICD-337. MOA cleanup script.
  scripts/clean-up-moa.sh
Labels: approved, lgtm

#432 SDCICD-341: Add provider list method, cleanup cluster command
  cmd/osde2e/cleanup/cmd.go
  cmd/osde2e/main.go
  pkg/common/providers/crc/crc.go
  pkg/common/providers/moaprovider/wrapped_calls.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/spi/provider.go
Labels: approved, lgtm

#433 SDCICD-337. Don't use docker for the cleanup script.
  scripts/clean-up-moa.sh
Labels: approved, lgtm

#434 SDCICD-337. Add in exports to clean up MOA script.
  scripts/clean-up-moa.sh
Labels: approved, lgtm

#435 SDCICD-341: Don't halt cleanup on single deletion error
  cmd/osde2e/cleanup/cmd.go
Labels: approved, lgtm

#436 Handle errors fetching cluster details from provider
  pkg/common/cluster/clusterutil.go
Labels: approved, lgtm

#437 SDCICD-343: Support setting ocm region to 'random'
  configs/region-random.yaml
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#438 SDCICD-344: Fix multierror usage
  pkg/common/cluster/clusterutil.go
  pkg/common/runner/service.go
Labels: approved, lgtm

#441 SDCICD-200. Remove prow test runner.
  ci/prow_run_tests.sh
Labels: approved, lgtm

#444 SDCICD-345: Add region to metadata and metrics
  pkg/common/metadata/metadata.go
  pkg/common/metadata/metadata_test.go
  pkg/e2e/metrics.go
  pkg/e2e/metrics_test.go
  pkg/e2e/setup.go
Labels: approved, lgtm

#445 Check if the vendor directory is up to date.
  scripts/check-vendor.sh
Labels: approved, lgtm

#447 vendor check fix.
  scripts/check-vendor.sh
Labels: approved, lgtm

#449 SDCICD-200. Make metrics upload automatic as part for prow runs.
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved

#443 SDCICD-200. Remove e2e focused make targets.
  Makefile
Labels: approved, lgtm

#451 SDCICD-349. Remove curator operator tests.
  pkg/e2e/operators/curator.go
Labels: approved, lgtm

#452 Add gather of test project state at end of run
  pkg/common/helper/helper.go
  pkg/common/helper/projects.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#454 SDCICD-354. Make sure cluster health checks fire for MOA clusters.
  pkg/common/cluster/clusterutil.go
Labels: approved

#455 SDCICD-355. Always load log-metrics at startup.
  pkg/common/load/load.go
Labels: approved, lgtm

#453 Fix recording both success and failure events on failure.
  pkg/common/events/events.go
  pkg/common/events/events_test.go
Labels: approved, lgtm

#457 SDCICD-357. Support install version delta from default.
  pkg/common/config/config.go
  pkg/common/versions/installselectors/delta_release_from_default.go
Labels: approved, do-not-merge/hold, lgtm

#458 SDCICD-357. Handle version out of bounds error.
  pkg/common/versions/installselectors/delta_release_from_default.go
Labels: approved, lgtm

#456 Create and delete functions for osde2ectl
  cmd/osde2ectl/create/cmd.go
  cmd/osde2ectl/delete/cmd.go
  cmd/osde2ectl/extend/cmd.go
  cmd/osde2ectl/get/cmd.go
  cmd/osde2ectl/list/cmd.go
  cmd/osde2ectl/main.go
  go.sum
  pkg/common/cluster/clusterutil.go
  pkg/common/providers/crc/crc.go
  pkg/common/providers/moaprovider/wrapped_calls.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/spi/cluster.go
  pkg/common/spi/provider.go
  pkg/common/versions/version_setup.go
  pkg/e2e/e2e.go
  pkg/e2e/setup.go
Labels: approved, lgtm

#459 SDCICD-299. Metrics library.
  go.sum
  pkg/metrics/addon_metadata.go
  pkg/metrics/addon_metadata_test.go
  pkg/metrics/client.go
  pkg/metrics/client_test.go
  pkg/metrics/events.go
  pkg/metrics/events_test.go
  pkg/metrics/junitresult.go
  pkg/metrics/junitresult_test.go
  pkg/metrics/metadata.go
  pkg/metrics/metadata_test.go
  pkg/metrics/objects.go
  pkg/metrics/objects_test.go
Labels: approved, lgtm

#461 SDCICD-343: Update viper with selected region
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#460 Support for extend cluster expiry feature in osde2ectl
  cmd/osde2ectl/extend/cmd.go
Labels: approved, lgtm

#462 SDCICD-359. Redirect output to report directory.
  go.mod
  pkg/e2e/e2e.go
Labels: approved, lgtm

#463 SDCICD-360. Replace whitelists with allowlists.
  pkg/common/config/config.go
  pkg/common/report/generate_report.go
  scripts/weather-report-to-slack.sh
Labels: approved, lgtm

#465 e2e tests for machinehealthchecks
  go.mod
  go.sum
  pkg/common/helper/clientsets.go
  pkg/e2e/osd/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/LICENSE
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/consts.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machineset.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
Labels: approved, lgtm

#442 Added velero backup check test.
  go.mod
  go.sum
  pkg/e2e/operators/managedvelero.go
  vendor/github.com/vmware-tanzu/velero/LICENSE
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/backup.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/backup_storage_location.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/constants.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/delete_backup_request.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/doc.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/download_request.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/labels_annotations.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/pod_volume_backup.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/pod_volume_operation_progress.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/pod_volume_restore.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/register.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/restic_repository.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/restore.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/schedule.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/server_status_request.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/volume_snapshot_location.go
  vendor/github.com/vmware-tanzu/velero/pkg/apis/velero/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash
