Repository openshift/osde2e, pull requests merged in 2020-01, with the labels that each got.

#196 SDCICD-89. Restore addon installation logic.
  go.mod
  go.sum
  pkg/osd/cluster.go
  pkg/osd/osd.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.adoc
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/README.adoc
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/current_access_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/current_access_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.json
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/root_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/root_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/subscription_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/subscription_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/subscription_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_request_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_response_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_response_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/access_review_response_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/openapi.json
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_request_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_response_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_response_reader.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/self_access_review_response_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.json
  vendor/github.com/openshift-online/ocm-sdk-go/errors/errors.go
  vendor/github.com/openshift-online/ocm-sdk-go/go.mod
  vendor/github.com/openshift-online/ocm-sdk-go/go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#198 SDCICD-123. Use cluster image sets for upgrades if specified.
  common/version.go
  pkg/config/config.go
  pkg/metadata/metadata.go
  pkg/upgrade/releases.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#200 SDCICD-120: Install stable version on Int before upgrading to nightly
  common/version.go
  pkg/osd/versions.go
Labels: approved, lgtm, size/S

#201 SDCICD-128: Write to two different metadata.json files
  common/e2e.go
  pkg/events/events_test.go
Labels: approved, lgtm, size/XS

#202 SDCICD-123. Increase clean runs to 10.
  pkg/osd/cluster.go
Labels: approved, lgtm, size/S

#203 SDCICD-85. Updates for addon test harness work.
  common/e2e.go
  common/metrics.go
  common/metrics_test.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  suites/addons/testdata/addon-runner.template
Labels: approved, lgtm, size/L

#199 e2e test for testing newest Hive with a set of older ClusterImageSets
  common/version.go
  pkg/osd/versions.go
  suites/clusterimagesets/middle/imagesets_test.go
  suites/clusterimagesets/oldest/imagesets_test.go
Labels: approved, lgtm, size/L

#204 SDCICD-131. Skip metrics upload on rehearsal jobs.
  common/e2e.go
  pkg/events/events_test.go
Labels: approved, lgtm, size/M

#205 Revert "Add tests to ensure certain pods appear on infra nodes"
  test/verify/infranodes.go
Labels: approved, lgtm, size/M

#206 SDCICD-142 - Check for endpoints multiple times before failing
  pkg/runner/results.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: size/L

#207 SDCICD-109 - First pass at addon testing doc
  README.md
  docs/Addons.md
Labels: approved, lgtm, size/M

#208 SDCICD-144: Prepend test results with phase of test
  common/e2e.go
Labels: approved, lgtm, size/M

#209 SDCICD-138: Add additional pod health checks to runner jobs
  pkg/runner/pod.go
  pkg/runner/service.go
Labels: approved, lgtm, size/S

#211 SDCICD-146: Prep work for prow job
  Makefile
  suites/clusterimagesets/imagesets_test.go
  suites/clusterimagesets/oldest/imagesets_test.go
Labels: approved, size/M

#210 SDCICD-104. Introduce state, refactor mutable config fields.
  cmd/osde2e-docs/parse.go
  common/e2e.go
  common/e2e_test.go
  common/metrics.go
  common/metrics_test.go
  common/setup.go
  common/version.go
  pkg/config/config.go
  pkg/config/load.go
  pkg/helper/helper.go
  pkg/helper/operators.go
  pkg/helper/operators_test.go
  pkg/helper/runner.go
  pkg/load/load.go
  pkg/osd/cluster.go
  pkg/osd/quota.go
  pkg/state/state.go
  pkg/upgrade/releases.go
  pkg/upgrade/upgrade.go
  suites/addons/addons_test.go
  suites/clusterimagesets/imagesets_test.go
  suites/clusterimagesets/oldest/imagesets_test.go
  suites/e2e/e2e_test.go
  suites/scale/scale_test.go
  test/addons/addon_test_harness.go
  test/operators/certman.go
  test/operators/curator.go
  test/operators/operators.go
  test/operators/prunejob.go
  test/workloads/guestbook/guestbook.go
Labels: approved, lgtm, size/XXL
