Repository openshift/osde2e, pull requests merged in 2020-02, with the labels that each got.

#212 Remove outdated rolebinding
  test/operators/managedvelero.go
Labels: approved, lgtm, size/XS

#213 SDCICD-153. Remove stale metrics from the pushgateway.
  scripts/metrics-sync.sh
Labels: approved, lgtm, size/S

#214 SDCICD-129: Update metadata json file upon every metadata instance change
  common/e2e.go
  common/setup.go
  common/version.go
  pkg/metadata/metadata.go
  pkg/osd/cluster.go
  pkg/upgrade/releases.go
Labels: approved, lgtm, size/M

#215 SDCICD-157. Support using latest cluster image set for fresh installs.
  common/version.go
  pkg/config/config.go
Labels: approved, lgtm, size/S

#216 SDCICD-157. Skip upgrades if the versions are identical.
  common/e2e.go
  common/version.go
  pkg/state/state.go
Labels: approved, lgtm, size/S

#217 SDCICD-158. Increase health check window.
  pkg/osd/cluster.go
Labels: approved, lgtm, size/XS

#218 SDCICD-51: Support arbitrary metrics derived from log data
  common/e2e.go
  common/metrics.go
  pkg/config/config.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
Labels: approved, lgtm, size/L

#219 SDCICD-160: Add a wait loop to certman tests
  test/operators/certman.go
Labels: approved, lgtm, size/M

#220 Removing the certman test to not block CI.
  test/operators/certman.go
Labels: approved, lgtm, size/M

#222 SDCICD-161. Fix cluster image set upgrade logic.
  common/e2e.go
Labels: approved, lgtm, size/XS

#223 SDCICD-162 - Automatically update to fast-x.y channel
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#224 SDCICD-162: Retrieve latest object
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#225 SDCICD-163. Make cluster image set tests work.
  Makefile
  suites/clusterimagesets/middle/imagesets_test.go
  suites/clusterimagesets/oldest/imagesets_test.go
Labels: approved, lgtm, size/M

#226 Add test to verify volume expansion
  test/verify/storage.go
Labels: approved, lgtm, size/S

#228 restoring the certman test
  test/operators/certman.go
Labels: approved, lgtm, size/M

#229 SDCICD-166. Fix workload test for middle/oldest CIS tests.
  Makefile
  suites/middleclusterimageset/imagesets_test.go
  suites/oldestclusterimageset/imagesets_test.go
Labels: approved, lgtm, size/XS

#227 SDCICD-165 - Poll result list or fail gracefully
  pkg/runner/results.go
Labels: approved, lgtm, size/S

#230 Added checkSecrets assistant function
  test/operators/operators.go
Labels: approved, lgtm, size/S

#232 SDCICD-168: Add timetoupgraded metric and ensure timetoinstall is honored
  pkg/metadata/metadata.go
  pkg/osd/cluster.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#233 SDCICD-171. Use composable configs instead of separate exeuction paths.
  Makefile
  common/setup.go
  common/version.go
  configs/addon-suite.yaml
  configs/conformance-suite.yaml
  configs/dry-run.yaml
  configs/e2e-suite.yaml
  configs/int.yaml
  configs/prod.yaml
  configs/scale-suite.yaml
  configs/skip-health-checks.yaml
  configs/stage.yaml
  configs/use-middle-version.yaml
  configs/use-oldest-version.yaml
  e2e_test.go
  pkg/config/config.go
  pkg/load/load.go
  pkg/osd/versions.go
  test/addons/addon_test_harness.go
  test/openshift/openshift.go
  test/operators/certman.go
  test/operators/configurealertmanager.go
  test/operators/curator.go
  test/operators/managedvelero.go
  test/operators/prunejob.go
  test/scale/nodevertical.go
  test/state/mustgather.go
  test/state/prometheus.go
  test/state/state.go
  test/verify/imagestreams.go
  test/verify/pods.go
  test/verify/projects.go
  test/verify/routes.go
  test/verify/storage.go
  test/workloads/guestbook/guestbook.go
Labels: approved, lgtm, size/L

#234 SDCICD-169: Don't compare semver if upgrading to a nightly
  common/version.go
Labels: approved, lgtm, size/XS

#236 Fixes the guestbook tests.
  Makefile
  pkged.go
  runner/e2e_test.go
  suites/addons/addons_test.go
  suites/middleclusterimageset/imagesets_test.go
  suites/oldestclusterimageset/imagesets_test.go
  suites/scale/scale_test.go
Labels: approved, size/L

#235 SDCICD-170: Trap BeforeSuite failures, bubble up ginkgo suite results
  common/e2e.go
  common/setup.go
Labels: approved, lgtm, size/M

#237 Add PagerDuty e2e test and fix dockerfile
  Dockerfile
  test/operators/pagerduty.go
Labels: approved, lgtm, size/S

#238 Added DeadMansSnitch operator test case
  test/operators/deadmanssnitch.go
Labels: approved, lgtm, size/S

#239 SDCICD-172: Copy files to a tmp dir and then tar them up
  test/state/prometheus.go
Labels: approved, lgtm, size/XS

#243 SDCICD-159: Start generating metrics based on logs
  Makefile
  configs/log-metrics.yaml
  pkg/e2e/e2e.go
Labels: approved, lgtm, size/S

#244 SDCICD-182. Introduce osde2e command and subcommands.
  Makefile
  README.md
  cmd/osde2e-docs/Options.md.tmpl
  cmd/osde2e-docs/docs.go
  cmd/osde2e-docs/main.go
  cmd/osde2e-docs/parse.go
  cmd/osde2e/main.go
  cmd/osde2e/test/test.go
  go.mod
  go.sum
  pkg/common/load/load.go
  pkg/e2e/addons/addon_test_harness.go
  pkg/e2e/e2e.go
  pkg/e2e/metrics_test.go
  pkg/e2e/setup.go
  runner/e2e_test.go
  vendor/github.com/google/subcommands/CONTRIBUTING
  vendor/github.com/google/subcommands/LICENSE
  vendor/github.com/google/subcommands/README.md
  vendor/github.com/google/subcommands/go.mod
  vendor/github.com/google/subcommands/subcommands.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#245 SDCICD-182. Make sure the out directory is created before building.
  Makefile
Labels: approved, lgtm, size/XS

#242 Test upgrades of SRE operators
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/dedicatedadmin.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm, size/L

#247 Remove osde2e-scale from Dockerfile.
  Dockerfile
Labels: approved, lgtm, size/XS

#249 SDCICD-190. Handle OCM API metrics, test files.
  scripts/metrics-sync.sh
Labels: approved, lgtm, size/M

#240 SDCICD-20. Expand scale tests.
  Makefile
  artifacts/scale/scale-runner.template
  ci/prow_run_tests.sh
  configs/long-timeout.yaml
  configs/scale-nodes-and-pods-suite.yaml
  configs/scale-performance-suite.yaml
  configs/scale-suite.yaml
  pkg/common/config/config.go
  pkg/common/runner/git.go
  pkg/e2e/scale/nodes_and_pods.go
  pkg/e2e/scale/nodevertical.go
  pkg/e2e/scale/performance.go
  pkg/e2e/scale/scale.go
  pkged.go
Labels: approved, lgtm, size/L

#251 SDCICD-192. Fix osde2e CLI bugs.
  pkg/e2e/e2e.go
Labels: approved, lgtm, size/S
