Repository openshift/osde2e, pull requests merged in 2021-12, with the labels that each got.

#937 SDCICD-700: Support GCP CCS clusters
  go.mod
  go.sum
  pkg/common/load/load.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
Labels: approved, lgtm

#942 Update OWNERS
  OWNERS
Labels: approved, lgtm

#943 Add Non-Privileged Namespace Setup Back
  pkg/e2e/verify/namespace_webhook.go
Labels: approved

#945 Clean up stale grpcurl-query pods if they exist
  assets/registry/replaces.template
Labels: approved, lgtm

#944 Ignore recently-created pods in health check
  pkg/common/cluster/healthchecks/pod_predicates.go
  pkg/common/cluster/healthchecks/pods.go
Labels: approved, lgtm

#932 Updated pr osd 7617: removed sleep statements as reviews suggested https://github.com/openshift/osde2e/pull/922
  pkg/e2e/operators/cloudingress/certificate.go
  pkg/e2e/operators/cloudingress/deletetapps2.go
  pkg/e2e/operators/cloudingress/dnsname.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
  pkg/e2e/operators/cloudingress/routeSelector.go
  pkg/e2e/operators/cloudingress/secondary_router.go
Labels: approved, lgtm

#946 OSD-9330 muo owner update to team
  pkg/e2e/operators/managedupgrade.go
Labels: approved, lgtm

#947 OSD-9333 update owner of CAO
  pkg/e2e/operators/configurealertmanager.go
Labels: approved, lgtm

#951 OSD-9332 OSD-9336 updating aurora ownership
  pkg/e2e/operators/cloudingress/cloudingress.go
  pkg/e2e/operators/mustgather.go
Labels: approved, lgtm, needs-ok-to-test

#956 OSD-9335 MVO owners update
  pkg/e2e/operators/managedvelero.go
Labels: approved, lgtm, needs-ok-to-test

#957 Added new url logic incase the job being ran is a PR-Check
  ci/prow_pr_check.sh
  cmd/osde2e/test/cmd.go
  configs/pr-check.yaml
  pkg/common/config/config.go
  pkg/debug/diff.go
Labels: approved, lgtm

#952 OSD-9339 updating orange ownership
  pkg/e2e/operators/routemonitor.go
Labels: approved, lgtm, needs-ok-to-test

#953 Update Splunk Forwarder Operator Owners
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm, needs-ok-to-test

#954 OSD-9331 certman-operator update owner
  pkg/e2e/operators/certman.go
Labels: approved, lgtm, needs-ok-to-test

#955 OSD-9334 update CDO owners
  pkg/e2e/operators/customdomains.go
Labels: approved, lgtm, needs-ok-to-test

#938 SDCICD-706: wait for a latestCSV status before moving forward or fail
  pkg/e2e/operators/operators.go
Labels: approved, lgtm, needs-ok-to-test
