Repository openshift/osde2e, pull requests merged in 2022-04, with the labels that each got.

#1090 Enable new addon_test_harness to be pulled on the same cluster
  assets/addons/addon-runner.template
Labels: approved

#1094 SDCICD-772 allow ReleaseAccepted as a valid CVO condition
  pkg/common/cluster/healthchecks/clusterversionoperator.go
  pkg/common/cluster/healthchecks/clusterversionoperator_test.go
Labels: approved, lgtm

#1095 ROSA CLI Update
  go.mod
  go.sum
Labels: approved

#1103 Replaced new id
  ci/prow_pr_check.sh
Labels: needs-ok-to-test

#1099 Adding a regex feature to machine type selector
  ci/prow_pr_check.sh
  docs/Config.md
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
  pkg/common/providers/rosaprovider/config.go
Labels: approved

#1098 osd-8474 e2e test added for GCP CIO load balancer reconcile
  go.mod
  go.sum
  pkg/common/helper/helper.go
  pkg/e2e/operators/cloudingress/rhapi_lb.go
Labels: approved, lgtm

#1106 Workaround to use the osdCcsAdmin AWS account at scale
  docs/Config.md
  pkg/common/aws/utils.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
Labels: approved

#1112 Making the CCS scale more readable
  pkg/common/aws/utils.go
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved

#1113 Cleaned CCS scale some more and increased time
  pkg/common/aws/utils.go
  pkg/common/providers/ocmprovider/cluster.go
Labels: needs-ok-to-test

#1115 Removed uneeded break statement
  pkg/common/aws/utils.go
Labels: approved
