Repository openshift/osde2e, pull requests merged in 2022-05, with the labels that each got.

#1118 Double the number of dependabot PRs
  .github/dependabot.yml
Labels: approved

#1136 WIP Updated PR job cluster
  ci/prow_pr_check.sh
  pkg/common/aws/utils.go
Labels: approved, do-not-merge/work-in-progress, needs-ok-to-test

#1117 Remove clusterwide pod healthcheck
  pkg/common/cluster/clusterutil.go
  pkg/common/cluster/healthchecks/pods.go
  pkg/common/cluster/healthchecks/pods_test.go
Labels: approved, lgtm

#1007 Deployment-Validation-Operator e2e testing
  pkg/e2e/operators/dvo.go
Labels: approved, lgtm

#1142 Updated pr cluster
  ci/prow_pr_check.sh
Labels: needs-ok-to-test

#1116 [OHSS-10233] Initial FedRAMP configuration file
  configs/fedramp.yaml
Labels: approved, lgtm

#1140 Remove unneeded dependency on promlog
  go.sum
  pkg/common/aws/session.go
Labels: approved, lgtm

#1141 Update go-pagerduty dependency
  cmd/ci-watcher-report/main.go
  go.mod
  go.sum
  pkg/common/pagerduty/pagerduty.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1145 OSD-8788 Add proxy test suite and day-2 add-proxy test
  cmd/osde2e/test/cmd.go
  configs/proxy-suite.yaml
  docs/Config.md
  pkg/common/config/config.go
  pkg/common/providers/crc/crc.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/proxy.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
  pkg/e2e/proxy/postinstall.go
Labels: approved, lgtm

#1150 Pods should be Running or Succeeded
  ci/prow_pr_check.sh
  pkg/e2e/verify/pods.go
Labels: approved, lgtm

#1153 [OSD-11101] add testing for remove proxy
  pkg/e2e/proxy/postinstall.go
Labels: approved, lgtm

#1162 pr-check updates
  ci/prow_pr_check.sh
  cmd/osde2e/test/cmd.go
  configs/pr-check.yaml
  pkg/common/cluster/pr_check_queue.go
  pkg/common/clusterproperties/properties.go
  pkg/common/config/config.go
  pkg/debug/diff.go
  pkg/e2e/e2e.go
Labels: approved

#1174 Removed Michael Wilson and moved to Diego.
  pkg/e2e/scale/mastervertical.go
  pkg/e2e/scale/nodes_and_pods.go
  pkg/e2e/scale/performance.go
  pkg/e2e/state/alerts.go
Labels: needs-ok-to-test

#1163 [OSD-11524] enable cluster provision with proxy enabled for osd and rosa
  docs/Config.md
  go.mod
  pkg/common/config/config.go
  pkg/common/providers/crc/crc.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/ocm.go
  pkg/common/providers/ocmprovider/proxy.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/config.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
  pkg/e2e/operators/cloudingress/rhapi_endpoint.go
  pkg/e2e/osd/dedicatedadmin.go
  pkg/e2e/proxy/postinstall.go
Labels: approved, lgtm

#1183 Only gather project/olm state if must-gather is enabled
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1191 Ignore failed pods that are owned by revision status
  pkg/e2e/verify/pods.go
Labels: approved, lgtm
