Repository openshift/osde2e, pull requests merged in 2022-03, with the labels that each got.

#1055 Add a way to specify the ADDON_PARAMETERS in secret as addon-parameters
  pkg/common/config/config.go
Labels: approved, lgtm

#1038 Adds test to verify certificate replacement
  pkg/e2e/operators/customdomains.go
Labels: approved, lgtm

#1045 rosaprovider: Use new --network-type option
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1058 CCS fails due to faulty overwrites.
  pkg/common/cluster/clusterutil.go
  pkg/common/load/load.go
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved

#1064 add recommendation to have multiple test pipelines to provide early w…
  docs/Addons.md
Labels: approved

#1068 [OHSS-10367] Handle edge case for standalone pod resources
  pkg/common/cluster/healthchecks/pods.go
  pkg/common/cluster/healthchecks/pods_test.go
Labels: approved, lgtm

#1066 pkg/common/cluster/healthchecks/pods: Include namespace in error messages
  pkg/common/cluster/healthchecks/pods.go
Labels: approved, lgtm

#1069 [OHSS-10367] CheckClusterPodHealth was incorrectly passing non-pending pods along
  pkg/common/cluster/healthchecks/pod_predicates.go
  pkg/common/cluster/healthchecks/pods.go
  pkg/common/cluster/healthchecks/pods_test.go
Labels: approved, lgtm

#1070 Allow dependabot to run tests
  .github/dependabot.yml
Labels: approved, lgtm

#1073 Fix misleading log message as completed pods have not been filtered out yet
  pkg/common/cluster/healthchecks/pods.go
Labels: approved, lgtm

#1075 Adding instructions on running addons locally
  docs/Addons.md
Labels: approved, needs-ok-to-test

#1074 [OSD-10334] Add ocm-agent test suite
  pkg/e2e/operators/ocmagent.go
Labels: approved, lgtm

#1077 Update MHC tests
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#1079 Will load aws creds from vault
  ci/prow_pr_check.sh
Labels: needs-ok-to-test

#1081 Assert full configuration of MHCs
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#1089 Added timeouts to the SplunkForwarder Jobs
  ci/prow_pr_check.sh
  pkg/e2e/operators/splunkforwarder.go
Labels: approved

#1084 helper: avoid test panic on CreateProject method
  pkg/common/helper/helper.go
Labels: approved, lgtm, ok-to-test
