Repository openshift/osde2e, pull requests merged in 2022-06, with the labels that each got.

#1178 OSD-11365 - Add test for techpreviewnoupgrade webhook
  pkg/e2e/verify/techpreviewnoupgrade_webhook.go
Labels: approved, lgtm, ok-to-test

#1204 Add control config param for proxy-based installs
  docs/Config.md
  pkg/common/config/config.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/proxy/postinstall.go
Labels: approved, lgtm

#1210 OSDe2e secrets that contain a certificate should pass the mounted filename.
  pkg/common/load/load.go
Labels: approved

#1217 Fix code panic in ROSA day-2 proxy calls
  pkg/common/providers/rosaprovider/wrapped_calls.go
Labels: approved, lgtm
