Repository openshift/osde2e, pull requests merged in 2022-11, with the labels that each got.

#1346 SDCICD-821 - DestroyAfterTest flag Debug
  pkg/common/cluster/clusterutil.go
  pkg/common/config/config.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1356 migrate from pkger to native go embed feature
  Makefile
  assets/assets.go
  cmd/osde2e/helpers/helpers.go
  cmd/osde2e/main.go
  cmd/osde2ectl/main.go
  configs/configs.go
  docs/Writing-Tests.md
  go.mod
  go.sum
  package.go
  pkg/common/helper/addons.go
  pkg/common/helper/workloads.go
  pkg/common/helper/workloads_test.go
  pkg/common/load/load.go
  pkg/common/providers/mock/mock.go
  pkg/common/templates/templates.go
  pkg/common/upgrade/managed.go
  pkg/e2e/operators/operators.go
  pkg/e2e/scale/scale.go
  pkg/e2e/verify/sccs.go
  pkg/e2e/workloads/guestbook/guestbook.go
  pkg/e2e/workloads/redmine/redmine.go
  pkg/reporting/templates/list_templates.go
  pkg/reporting/templates/template_cache.go
  scripts/include-pkger.sh
Labels: approved, lgtm

#1347 bump go requirement to 1.18
  go.mod
  go.sum
Labels: approved, lgtm

#1361 bump golangci-lint to v1.50.1
  .golang-ci.yml
  Makefile
Labels: approved, lgtm

#1362 add jbpratt to reviewers/approvers
  OWNERS
Labels: approved, lgtm

#1360 actually use failure threshold for alerts
  pkg/common/alert/alert.go
Labels: approved, lgtm

#1363 fix core/v1 api imported twice
  pkg/common/helper/helper.go
Labels: approved, lgtm

#1358 SDCICD-760: remove unneeded sts account setup
  go.mod
  go.sum
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/operators/cloudingress/rhapi_lb.go
Labels: approved, lgtm, ok-to-test

#1376 Bump osde2e dockerfile parent images tags
  Dockerfile.osde2e
Labels: approved, lgtm

#1377 remove osde2ectl
  Dockerfile.osde2ectl
  Makefile
  README.md
  cmd/osde2ectl/create/cmd.go
  cmd/osde2ectl/delete/cmd.go
  cmd/osde2ectl/expire/cmd.go
  cmd/osde2ectl/extend/cmd.go
  cmd/osde2ectl/get/cmd.go
  cmd/osde2ectl/healthcheck/cmd.go
  cmd/osde2ectl/list/cmd.go
  cmd/osde2ectl/main.go
  docs/Config.md
  scripts/run-sd-scale-test.sh
Labels: approved, lgtm

#1372 fix common/runner importing random log package
  go.mod
  pkg/common/runner/service.go
Labels: approved, lgtm

#1382 e2e/verify: remove pending oauth tokens tests
  pkg/e2e/verify/oauth_tokens.go
Labels: approved, lgtm

#1384 common/logging: add Lshortfile flag for consistency
  pkg/common/logging/logging.go
Labels: approved, lgtm

#1385 Handle error when writing metrics to s3 bucket for cluster properties
  pkg/common/aws/s3.go
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#1386 various logging cleanup
  pkg/common/runner/runner.go
  pkg/e2e/addons/addon_test_harness.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1383 providers/ocmprovider: remove ccs overwrite logic
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
Labels: approved, lgtm

#1380 support setting ginkgo loglevel
  docs/Config.md
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1399 common/providers: remove CRC
  configs/crc.yaml
  docs/Config.md
  docs/Writing-Tests.md
  go.mod
  go.sum
  pkg/common/providers/crc/config.go
  pkg/common/providers/crc/crc.go
  pkg/common/providers/ocmprovider/environments.go
  pkg/common/providers/ocmprovider/ocm.go
  pkg/common/providers/providers_generated.go
Labels: approved, lgtm

#1397 AWS credentials config consolidation
  docs/Config.md
  pkg/common/aws/s3.go
  pkg/common/aws/s3_session.go
  pkg/common/aws/session.go
  pkg/common/aws/utils.go
  pkg/common/config/aws_config.go
  pkg/common/config/config.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/config.go
  pkg/common/providers/rosaprovider/util.go
Labels: approved, lgtm, tide/merge-method-squash

#1401 Documentation Updates
  README.md
  docs/Config.md
Labels: approved, lgtm

#1405 e2e/operators/cloudingress: skip on STS
  pkg/e2e/operators/cloudingress/apischeme_cr.go
  pkg/e2e/operators/cloudingress/certificate.go
  pkg/e2e/operators/cloudingress/deletetapps2.go
  pkg/e2e/operators/cloudingress/dnsname.go
  pkg/e2e/operators/cloudingress/installed.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
  pkg/e2e/operators/cloudingress/rhapi_endpoint.go
  pkg/e2e/operators/cloudingress/routeSelector.go
  pkg/e2e/operators/cloudingress/secondary_router.go
  pkg/e2e/operators/cloudingress/upgrade.go
Labels: approved, lgtm

#1408 Reformat Config.md
  docs/Config.md
Labels: approved, lgtm

#1410 Add ryankwilliams to reviewers and approvers
  OWNERS
Labels: approved, lgtm

#1409 OSD-13922 update machinehealthcheck tests for metal instance support
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#1411 Remove unneeded dedicated-admin tests
  pkg/e2e/osd/dedicatedadmin.go
Labels: approved, lgtm

#1403 Adds test to verify Hypershift Install
  cmd/osde2e/test/cmd.go
  pkg/common/aws/ec2.go
  pkg/e2e/openshift/hypershift/verifyInstall.go
Labels: approved, lgtm

#1412 common/util: set ginkgo.Offset for GinkgoIt helper
  pkg/common/util/util.go
Labels: approved, lgtm

#1415 e2e/verify/prom_exporters: skip on STS
  pkg/e2e/verify/prom_exporters.go
Labels: approved, lgtm

#1418 Hypershift clusters require BYOVPC
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved

#1416 e2e/operators/dvo: delete ns afterall
  pkg/e2e/operators/dvo.go
Labels: approved, lgtm

#1417 misc: bump dependencies
  go.mod
  go.sum
  pkg/common/helper/clientsets.go
  pkg/common/runner/pod.go
  pkg/common/upgrade/managed.go
  pkg/e2e/operators/cloudingress/apischeme_cr.go
  pkg/e2e/operators/cloudingress/deletetapps2.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
  pkg/e2e/operators/cloudingress/rhapi_endpoint.go
  pkg/e2e/operators/cloudingress/secondary_router.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/splunkforwarder.go
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#1419 Add support for using ginkgo labels
  cmd/osde2e/test/cmd.go
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1404 [OSD-13651] add test for dedicated admin can patch console
  pkg/e2e/osd/dedicatedadmin.go
Labels: approved, lgtm, tide/merge-method-squash

#1424 Use proper machine api
  go.mod
  go.sum
  pkg/common/cluster/healthchecks/machines.go
Labels: approved, lgtm

#1413 common: load kubeconfig on helper setup
  pkg/common/config/config.go
  pkg/common/helper/helper.go
Labels: approved, lgtm

#1425 Update and trim dependencies
  go.mod
  go.sum
Labels: approved, lgtm

#1430 OSDe2e update hypershift un/install times
  pkg/common/cluster/clusterutil.go
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved

#1431 poll for rolebinding rather than sleep
  pkg/common/helper/helper.go
Labels: approved, lgtm
