Repository openshift/osde2e, pull requests merged in 2023-09, with the labels that each got.

#2096 versions: triggered nightly versions need -nightly appended
  pkg/common/versions/installselectors/triggered_nightlies.go
Labels: approved

#2080 added yiqin to reviewers
  OWNERS
Labels: approved, lgtm, tide/merge-method-squash

#2089 Update the osde2e-common dependency
  go.mod
  go.sum
Labels: approved, lgtm

#2109 e2e: skip customdomains on >= 4.13
  pkg/e2e/operators/customdomains.go
Labels: approved, lgtm

#2111 e2e: increase hibernation time for nightly clusters
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2112 installselectors: use regex to find nightly version from jobid
  pkg/common/versions/installselectors/triggered_nightlies.go
Labels: approved, lgtm

#2113 OWNERS update
  OWNERS
Labels: approved, lgtm

#2124 added rosa.env to int config
  configs/int.yaml
Labels: approved, lgtm

#2125 e2e: remove state gathering
  pkg/common/helper/state.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2126 debug: fix getLastJobID
  pkg/debug/diff.go
Labels: approved, lgtm

#2134 sdcicd-1075 added generic test harness resource template for saas pipeline
  ci/acceptance-tests-template.yaml
Labels: approved

#2130 debug: fix getLastJobID search for job ID
  pkg/debug/diff.go
Labels: approved, lgtm

#2141 common/runner: use ginkgo logr by default
  go.mod
  pkg/common/helper/helper.go
  pkg/common/helper/pods.go
  pkg/common/runner/pod.go
  pkg/common/runner/runner.go
  pkg/common/runner/service.go
  pkg/e2e/operators/dvo.go
Labels: approved, lgtm

#2136 config: fix BASE_JOB_URL default value
  pkg/common/config/config.go
Labels: approved, lgtm

#2139 e2e/operators: use common operator upgrade function
  go.mod
  go.sum
  pkg/e2e/operators/configurealertmanager/configurealertmanager.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#2137 e2e/osd: remove firewall cmd log
  pkg/e2e/osd/ocm.go
Labels: approved, lgtm

#2152 misc: bump osde2e-common
  go.mod
  go.sum
Labels: approved, lgtm

#2153 debug: fix pathing to dependencies.txt
  pkg/debug/diff.go
Labels: approved, lgtm

#2138 e2e: only generate deps on periodic jobs
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2150 osd: remove firewall delete log
  pkg/e2e/osd/ocm.go
Labels: approved, lgtm
