Repository openshift/osde2e, pull requests merged in 2023-04, with the labels that each got.

#1678 Exit with failure if version cannot be chosen
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1719 Fix spelling error with test harness and include a new label
  configs/test-harness.yaml
  pkg/common/label/label.go
  pkg/e2e/harness_runner/harness_runner.go
Labels: approved, lgtm

#1724 SDCICD-956: Skip configure alertmanager operator secret exists tests for nightly build clusters
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/spi/cluster.go
  pkg/e2e/e2e.go
  pkg/e2e/operators/configurealertmanager/configurealertmanager.go
Labels: approved, lgtm, jira/valid-reference

#1727 Provision for addon-metadata files created in addon harnesses
  pkg/common/metadata/metadata.go
Labels: approved, lgtm

#1732 Wait for dedicated-admins-cluster clusterrole to exists for scc tests
  pkg/e2e/verify/sccs.go
Labels: approved, lgtm

#1722 SDCICD-959: Extend the use of AWS profiles where access key/secret access key are used
  pkg/common/aws/session.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/rosa.go
Labels: approved, lgtm, jira/valid-reference

#1725 bump ocm-sdk-go to v0.1.330 and rosa to v1.2.16
  go.mod
  go.sum
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/config.go
Labels: approved, lgtm

#1746 verify/pods: ignore pods that are in osde2e prefixed namespaces
  pkg/e2e/verify/pods.go
Labels: approved, lgtm

#1752 helper: introduce retries when attempting to fetch namespace from server
  pkg/common/helper/helper.go
Labels: approved, lgtm

#1753 e2e/workloads: bump timeout and improve err desc
  pkg/e2e/workloads/workloads.go
Labels: approved, lgtm

#1756 Remove rosa non sts periodic job from list of active jobs
  docs/CI-Jobs.md
Labels: approved, lgtm

#1767 SDCICD-971: add an option to toggle on/off running post upgrade tests
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm, jira/valid-reference

#1768 Bump ocm-sdk-go to version 0.1.333
  go.mod
  go.sum
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#1772 Use policy v1 api over v1beta1 for pod disruption budget
  assets/workloads/e2e/pdb/pdb-1.yaml
  assets/workloads/e2e/pdb/pdb-2.yaml
  pkg/common/helper/workloads.go
Labels: approved, lgtm

#1773 common/helper/testrunner: expose OCM_CLUSTER_ID env
  assets/tests/tests-runner.template
  pkg/common/helper/testRunner.go
Labels: approved, lgtm

#1771 SDCICD-977 access AWS account ID through CCS session struct
  docs/Config.md
  pkg/common/aws/session.go
  pkg/common/config/aws_config.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/oidcconfig.go
Labels: approved, lgtm, tide/merge-method-squash

#1774 added job script for parameterized job
  scripts/parameterized-job.sh
Labels: approved, lgtm

#1778 changed script permissions to executable
  scripts/parameterized-job.sh
Labels: approved, lgtm

#1777 Add cluster gate agreement when performing cluster upgrades
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/ocm.go
  pkg/common/providers/ocmprovider/upgrades.go
  pkg/common/providers/rosaprovider/rosa.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
  pkg/common/upgrade/managed.go
  pkg/common/versions/common/utils.go
Labels: approved, lgtm

#1779 Add the ability to toggle on/off pre upgrade tests
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1782 Add new install version selectors for supporting upgrade workflows
  pkg/common/config/config.go
  pkg/common/providers/ocmprovider/versions.go
  pkg/common/versions/installselectors/latest_y_from_delta.go
  pkg/common/versions/installselectors/latest_z_from_delta.go
  pkg/common/versions/installselectors/utils.go
Labels: approved, lgtm

#1785 fixed report dir name
  scripts/parameterized-job.sh
Labels: approved, lgtm

#1786 Fix osd upgrade scenarios from being marked failed when all tests passed
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1791 adding more job params
  scripts/parameterized-job.sh
Labels: approved, lgtm

#1797 Consolidate and remove duplicate code for selecting cluster versions
  pkg/common/versions/installselectors/default_version.go
  pkg/common/versions/installselectors/default_version_test.go
  pkg/common/versions/version_selector.go
  pkg/common/versions/version_setup.go
  pkg/common/versions/versionselector.go
  pkg/e2e/e2e.go
  pkg/e2e/version.go
Labels: approved, lgtm

#1790 Update jobs documentation to reflect latest OSD upgrade CI jobs
  docs/CI-Jobs.md
Labels: approved, lgtm
