Repository openshift/osde2e, pull requests merged in 2023-05, with the labels that each got.

#1806 verify/storage.go: minor refinements to pvc test
  pkg/e2e/verify/storage.go
Labels: approved, lgtm

#1812 Set aws session when create/delete rosa hcp vpc
  pkg/common/providers/rosaprovider/vpc.go
Labels: approved, lgtm

#1807 SDCICD-923: Add support to automatically create rosa account roles
  pkg/common/providers/rosaprovider/accountroles.go
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm, jira/valid-reference

#1819 Bump go from 1.18 to 1.19
  Dockerfile.osde2e
  go.mod
Labels: approved, lgtm

#1820 Set cluster name var when creating through ROSA
  pkg/common/cluster/clusterutil.go
Labels: approved, lgtm

#1818 sdcicd-955 added new test config
  configs/complete-e2e.yaml
Labels: approved, lgtm

#1824 Do not attempt account role creation when unable to get account roles
  pkg/common/providers/rosaprovider/accountroles.go
Labels: approved, lgtm

#1800 Bump k8s.io/client-go package for other k8s package bumps
  go.mod
  go.sum
Labels: approved, lgtm

#1830 added new suite to run basic tests on new configs
  configs/sanity.yaml
Labels: approved, lgtm

#1829 Hotfix -Revert Rosa Back to v1.2.17
  go.mod
  go.sum
Labels: approved, lgtm

#1831 e2e/operators/ocmagent: update configmap name
  pkg/e2e/operators/ocmagent/ocmagent.go
Labels: approved, lgtm

#1838 Install git as its required to use terraform-exec within a container
  Dockerfile.osde2e
Labels: approved, lgtm

#1840 Include channel group when creating rosa account roles
  pkg/common/providers/rosaprovider/accountroles.go
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1833 Docs for self service jobs
  docs/Self-Service-MOPs/Ad-Hoc-E2E-Job.md
  docs/Self-Service-MOPs/Region-Enablement.md
  docs/Test-Harnesses.md
Labels: approved, lgtm, tide/merge-method-squash

#1843 Update CI jobs doc to include ROSA Classic STS TRT nightly jobs
  docs/CI-Jobs.md
Labels: approved, lgtm

#1842 Blurb and link to addon test harness testing
  docs/Test-Harnesses.md
Labels: approved, lgtm

#1861 added parameters to job script
  scripts/parameterized-job.sh
Labels: approved, lgtm

#1872 Update ci-jobs doc to reflect the slack channel for notifications
  docs/CI-Jobs.md
Labels: approved, lgtm

#1875 Explicitly pass the ROSA account roles when creating clusters
  pkg/common/providers/rosaprovider/accountroles.go
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm
