Repository openshift/osde2e, pull requests merged in 2023-01, with the labels that each got.

#1467 sdcicd-869 remove hardcoded timeouts, default timeout to POLLING_TIMEOUT
  pkg/common/util/util.go
  pkg/e2e/openshift/app_builds.go
  pkg/e2e/openshift/disruptive.go
  pkg/e2e/openshift/images.go
  pkg/e2e/verify/pods.go
  pkg/e2e/verify/storage.go
  pkg/e2e/verify/strict_transport_security.go
Labels: approved, lgtm, tide/merge-method-squash

#1496 HyperShift tests maintenance
  configs/hypershift.yaml
  pkg/e2e/openshift/hypershift/verifyInstall.go
Labels: approved, lgtm

#1499 Initialize variables using beforeall for hypershift install tests
  pkg/e2e/openshift/hypershift/verifyInstall.go
Labels: approved, lgtm

#1501 OSDe2e Versions - Updates to version Picker
  pkg/common/config/config.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1503 Enable node labels tests as part of hypershift suite
  pkg/e2e/osd/nodelabels.go
Labels: approved, lgtm, tide/merge-method-squash

#1502 e2e/workloads: refactor and simplify
  assets/workloads/e2e/guestbook/frontend-service.yaml
  assets/workloads/e2e/guestbook/guestbook-route.yaml
  assets/workloads/e2e/redmine/redmine-route.yaml
  cmd/osde2e/alert/cmd.go
  cmd/osde2e/test/cmd.go
  pkg/e2e/workloads/guestbook/guestbook.go
  pkg/e2e/workloads/redmine/redmine.go
  pkg/e2e/workloads/workloads.go
Labels: approved, lgtm

#1500 add terraform for BYOVPC
  assets/terraform/setup-vpc.tf
Labels: approved, lgtm

#1484 SDCICD-874 rework querying of operator catalogs
  assets/registry/replaces.template
  go.mod
  go.sum
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#1505 Enable privileged containers tests as part of hypershift suite
  pkg/e2e/osd/privileged.go
Labels: approved, lgtm

#1508 common/expect: fix NoError description
  pkg/common/expect/expect.go
Labels: approved, lgtm

#1515 common/cluster: perform ready healthcheck for rosa hypershift
  pkg/common/cluster/clusterutil.go
Labels: approved, lgtm

#1504 SDCICD-889: e2e/osd: enable daemonsets on hypershift
  pkg/e2e/osd/daemonsets.go
Labels: approved, lgtm

#1516 Remove node labels service definition test as part of hypershift suite
  pkg/e2e/osd/nodelabels.go
Labels: approved, lgtm

#1507 e2e/verify/routes: wait for console route to exist
  pkg/e2e/verify/routes.go
Labels: approved, lgtm

#1476 Apply test case standards to ocm agent operator tests
  cmd/osde2e/test/cmd.go
  configs/informing-suite.yaml
  pkg/common/helper/impersonate.go
  pkg/e2e/operators/ocmagent.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#1518 e2e/verify/routes: wait for respective deployment
  pkg/e2e/verify/routes.go
Labels: approved, lgtm

#1519 Remove openshift-v prefix from version option for rosa create cluster
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1521 e2e/operators: skip on hypershift
  pkg/e2e/operators/certman.go
  pkg/e2e/operators/cloudingress/apischeme_cr.go
  pkg/e2e/operators/cloudingress/certificate.go
  pkg/e2e/operators/cloudingress/deletetapps2.go
  pkg/e2e/operators/cloudingress/dnsname.go
  pkg/e2e/operators/cloudingress/installed.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
  pkg/e2e/operators/cloudingress/rhapi_endpoint.go
  pkg/e2e/operators/cloudingress/rhapi_lb.go
  pkg/e2e/operators/cloudingress/routeSelector.go
  pkg/e2e/operators/cloudingress/secondary_router.go
  pkg/e2e/operators/cloudingress/upgrade.go
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/dvo.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/mustgather.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/osdmetricsexporter.go
  pkg/e2e/operators/prunejob.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/routemonitor.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#1522 e2e/scale: disable on hypershift
  pkg/e2e/scale/mastervertical.go
  pkg/e2e/scale/nodes_and_pods.go
  pkg/e2e/scale/performance.go
Labels: approved, lgtm

#1523 common/helper: remove setting project print
  pkg/common/helper/helper.go
Labels: approved, lgtm

#1524 SDCICD-900 Swap concurrentviper to use viper alias
  pkg/e2e/operators/certman.go
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/dvo.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/mustgather.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/osdmetricsexporter.go
  pkg/e2e/operators/prunejob.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/routemonitor.go
Labels: approved, lgtm

#1520 SDCICD-848 - Fix OSD CCS Cluster Creation
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#1526 e2e/verify: wait for deployment to be created
  pkg/e2e/verify/routes.go
Labels: approved, lgtm

#1525 SDCICD-898: Use label filters for osde2e configs over focus strings
  README.md
  configs/e2e-suite.yaml
  configs/informing-suite.yaml
Labels: approved, lgtm

#1529 SDCICD-905: e2e/verify/routes - skip on hypershift
  pkg/e2e/verify/routes.go
Labels: approved, lgtm

#1528 SDCICD-903: Include retries when performing grpc query for operator bundle
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#1542 Swap dependabot back to daily
  .github/dependabot.yml
Labels: approved, lgtm

#1543 Change dependabot version to 2.
  .github/dependabot.yml
Labels: approved

#1530 SDCICD-915: support fips through rosaprovider
  configs/fedramp.yaml
  configs/fips.yaml
  pkg/common/config/config.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/verify/fips.go
Labels: approved, lgtm

#1546 SDCICD-848 - Fix OSD CCS flow
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#1553 Destroy cluster after tests with failures when flag is enabled
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1554 Extend grpc query for operator previous csv retries
  pkg/e2e/operators/operators.go
Labels: approved, lgtm
