Repository openshift/osde2e, pull requests merged in 2023-03, with the labels that each got.

#1648 SDCICD-940: Allow osde2e to workaround hypershift admin kubeconfig self cert bug
  pkg/common/config/config.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/kubeconfig.go
Labels: approved, lgtm, jira/valid-reference

#1640 SDCICD-937: Apply test standards to configure alert manager operator
  cmd/osde2e/test/cmd.go
  pkg/e2e/operators/configurealertmanager.go
  pkg/e2e/operators/configurealertmanager/configurealertmanager.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm, jira/valid-reference

#1625 Revised README
  README.md
  docs/OSDE2E-Testing.md
Labels: approved, lgtm

#1642 SDCICD-944: Rename destroy-cluster flag to skip-destroy-cluster
  cmd/osde2e/test/cmd.go
  docs/Config.md
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm, jira/valid-reference

#1655 SDCICD-939: Fix for rosa to use latest ocp version when not using stable channel
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm, jira/valid-reference

#1665 Comment for hypershift config regarding aws region
  configs/hypershift.yaml
Labels: approved, lgtm

#1610 SDCICD-933: Auto create ROSA hosted control plane VPC when undefined
  assets/terraform/setup-vpc.tf
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/vpc.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
  pkg/common/terraform/terraform.go
Labels: approved, lgtm, jira/valid-reference

#1672 Fix bug when attempting to delete aws vpc for hypershift clusters
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1673 Ignore custom configs used while working on development tasks
  .gitignore
Labels: approved, lgtm

#1682 set ginkgo suite timeout
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1694 bump suite timeout to 6 hours
  pkg/common/config/config.go
Labels: approved, lgtm

#1693 ordered operator installs
  pkg/e2e/operators/certman.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/mustgather.go
  pkg/e2e/operators/osdmetricsexporter.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/routemonitor.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#1690 Avoid panic error when specific image selector fails to parse version
  pkg/common/versions/installselectors/specific_image.go
  pkg/common/versions/version_selector.go
Labels: approved, lgtm

#1683 e2e/operators: collapse deployment install test
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#1699 Only create shared directory when env variable is defined
  pkg/e2e/e2e.go
Labels: approved, lgtm

#1697 deprecate util.GinkgoIt wrapper
  docs/Writing-Tests.md
  pkg/common/util/util.go
  pkg/common/util/versionutil.go
  pkg/e2e/addons/addon_test_harness.go
  pkg/e2e/openshift/app_builds.go
  pkg/e2e/openshift/conformance.go
  pkg/e2e/openshift/disruptive.go
  pkg/e2e/openshift/images.go
  pkg/e2e/operators/certman.go
  pkg/e2e/operators/cloudingress/apischeme_cr.go
  pkg/e2e/operators/cloudingress/installed.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
  pkg/e2e/operators/cloudingress/rhapi_endpoint.go
  pkg/e2e/operators/cloudingress/rhapi_lb.go
  pkg/e2e/operators/cloudingress/secondary_router.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/dvo.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/mustgather.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/prunejob.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/routemonitor.go
  pkg/e2e/operators/splunkforwarder.go
  pkg/e2e/osd/dedicatedadmin.go
  pkg/e2e/osd/inhibitions.go
  pkg/e2e/osd/machinehealthcheck.go
  pkg/e2e/osd/ocm.go
  pkg/e2e/osd/olm.go
  pkg/e2e/osd/rebalance_infra_nodes.go
  pkg/e2e/proxy/postinstall.go
  pkg/e2e/scale/performance.go
  pkg/e2e/state/alerts.go
  pkg/e2e/state/prometheus.go
  pkg/e2e/verify/encrypted_storage.go
Labels: approved, lgtm

#1698 operators/managedupgrade: move out of informing suite
  pkg/e2e/operators/managedupgrade.go
Labels: approved, lgtm

#1692 drop eol version contraints
  pkg/common/util/versionutil.go
  pkg/common/util/versionutil_test.go
  pkg/e2e/verify/prom_exporters.go
Labels: approved, lgtm

#1710 Add documentation for TRT OCP release gate jobs
  docs/Self-Service-MOPs/TRT-OCP-Release-Gating.md
Labels: approved, lgtm

#1705 New version selector to get latest X.Y version available
  pkg/common/config/config.go
  pkg/common/versions/installselectors/latest_xy.go
Labels: approved, lgtm

#1669 Convert Addon Harness to Test Harness - First Pass
  assets/tests/tests-runner.template
  cmd/osde2e/alert/cmd.go
  cmd/osde2e/test/cmd.go
  configs/addon-suite.yaml
  configs/test-harness.yaml
  docs/Config.md
  pkg/common/config/config.go
  pkg/common/helper/testRunner.go
  pkg/common/metadata/addon.go
  pkg/common/metadata/metadata.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/e2e/addons/addon_test_harness.go
  pkg/e2e/e2e.go
  pkg/e2e/harness_runner/harness_runner.go
  pkg/e2e/metrics.go
  pkg/e2e/metrics_test.go
Labels: approved, lgtm, tide/merge-method-squash, do-not-merge/hold

#1718 sdcicd-717 update suite name in readme
  docs/Config.md
Labels: approved, lgtm
