Repository openshift/osde2e, pull requests merged in 2023-07, with the labels that each got.

#1957 SDCICD-1019: remove rosa hcp periodic job from ci doc
  docs/CI-Jobs.md
Labels: approved, lgtm, jira/valid-reference

#1975 Allow cleanup command to clean up a specific cluster by id
  cmd/osde2e/cleanup/cmd.go
Labels: approved, lgtm

#1978 ROSA provider: perform rosa login prior to deleting cluster/resources
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1974 use describeTable for better running multi harness jobs SDCICD-955
  pkg/e2e/harness_runner/harness_runner.go
Labels: approved, lgtm, tide/merge-method-squash

#1982 Adds a new config for enabling rosa sts to deploy clusters
  configs/sts.yaml
Labels: approved, lgtm

#1987 update docs to reflect new skip-destroy-cluster env var
  docs/Config.md
Labels: approved, lgtm

#1989 added step to create harness quay repo
  docs/Test-Harnesses.md
Labels: approved, lgtm

#1988 Update self service doc for openshift release gate testing signal
  docs/Self-Service-MOPs/TRT-OCP-Release-Gating.md
Labels: approved, lgtm

#1995 Update ci jobs doc to reflect job renaming
  docs/CI-Jobs.md
Labels: approved, lgtm

#1942 osde2e operator harness job
  ci/acceptance-tests-template.yaml
Labels: approved, lgtm

#1996 harness batch job related updates
  configs/complete-e2e.yaml
  docs/Config.md
  pkg/common/label/label.go
  pkg/e2e/harness_runner/harness_runner.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/osdmetricsexporter.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm

#2005 Update MVO e2e tests
  go.mod
  go.sum
  pkg/e2e/operators/managedvelero.go
Labels: approved, lgtm

#2006 Remove workload tests from hypershift/e2e test suites
  pkg/e2e/workloads/workloads.go
Labels: approved, lgtm

#2009 Harness Runner: Handle Image Tags When Generating Job Name
  pkg/e2e/harness_runner/harness_runner.go
Labels: approved, lgtm

#2008 use suite timeout config for harness if provided, otherwise generic pollingtimeout
  pkg/e2e/harness_runner/harness_runner.go
Labels: approved, lgtm

#2014 fixes ` Found two adjacent labels.` error
  configs/complete-e2e.yaml
Labels: approved, lgtm

#2021 Test harness: fix handling the timeout for the harness pod
  pkg/e2e/harness_runner/harness_runner.go
Labels: approved, lgtm
