Repository openshift/osde2e, pull requests merged in 2023-06, with the labels that each got.

#1889 Jenkins ccs env var
  scripts/parameterized-job.sh
Labels: approved, lgtm, tide/merge-method-squash

#1851 fixed must gather flag not reading, corrected hibernate default
  README.md
  cmd/osde2e/test/cmd.go
  docs/Config.md
  pkg/common/config/config.go
  pkg/e2e/e2e.go
  scripts/parameterized-job.sh
Labels: approved, lgtm, tide/merge-method-squash

#1897 Fixes minimum compute node issue for multi AZ clusters
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1896 Updates Rosa and Terraform to unblock hcp pipelines
  assets/terraform/setup-vpc.tf
  go.mod
  go.sum
Labels: approved, lgtm

#1899 Adds managed false arg to oidc config create
  pkg/common/providers/rosaprovider/oidcconfig.go
Labels: approved, lgtm

#1832 Update CI-Jobs.md to reflect which AWS account is used for the job
  docs/CI-Jobs.md
Labels: approved, lgtm, tide/merge-method-squash

#1908 e2e/workloads: mark redmine test as pending
  pkg/e2e/workloads/workloads.go
Labels: approved, lgtm

#1916 Update Region-Enablement.md to include link to new jenkins SOP
  docs/Self-Service-MOPs/Region-Enablement.md
Labels: approved, lgtm

#1888 Validate HS MC & SC Upgrades Test Suite
  go.mod
  go.sum
  test/mcscupgrade/.gitignore
  test/mcscupgrade/Dockerfile
  test/mcscupgrade/Makefile
  test/mcscupgrade/README.md
  test/mcscupgrade/mcscupgrade_suite_test.go
  test/mcscupgrade/mcscupgrade_test.go
Labels: approved, lgtm

#1933 Bump osde2e-common to latest commit sha
  go.mod
  go.sum
  test/mcscupgrade/mcscupgrade_test.go
Labels: approved, lgtm

#1941 SDCICD-1019: Update CI jobs doc to reflect current active jobs
  docs/CI-Jobs.md
Labels: approved, lgtm, jira/valid-reference

#1945 Modify ROSA options for delete operator roles and oidc provider
  pkg/common/providers/rosaprovider/cluster.go
Labels: approved, lgtm

#1946 configs: set rosa.env to stage in stage config
  configs/stage.yaml
Labels: approved, lgtm

#1951 Fix the bug causing rosa cluster oidc config deletion to fail
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/oidcconfig.go
Labels: approved, lgtm

#1952 Update CI jobs doc to reflect new TRT nightly jobs
  docs/CI-Jobs.md
Labels: approved, lgtm
