Repository openshift/osde2e, pull requests merged in 2024-09, with the labels that each got.

#2684 SDCICD-1382 allow passing subnet IDs in jenkins gap analysis job
  scripts/gap-analysis-jobs.sh
Labels: approved, lgtm

#2668 [OSD-24748] SDN migration suite
  test/sdn_migration/OWNERS
  test/sdn_migration/README.md
  test/sdn_migration/sdn_migration_suite_test.go
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm, ok-to-test

#2685 fix param name for specific nightly in parameterized jenkins job template
  scripts/parameterized-job.sh
Labels: approved, lgtm

#2694 misc: bump osde2e common and gofumpt sdn_migration suite
  go.mod
  go.sum
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm

#2698 go.mod: bump to go 1.22
  .ci-operator.yaml
  go.mod
Labels: approved, lgtm

#2701 ci: remove unused scripts
  ci/aro-e2e-tests.sh
  ci/cleanup-aro-clusters.sh
  ci/create-aro-cluster-ovn.sh
  ci/create-aro-cluster.sh
  ci/create-ocp-cluster.sh
  ci/create-osd-cluster.sh
  ci/create-rosa-cluster.sh
  ci/delete-osd-cluster.sh
  ci/delete-rosa-cluster.sh
  ci/destroy-aro-cluster.sh
  ci/destroy-ocp-cluster.sh
  ci/osd-conformance.sh
  ci/prow-ocm-adoption.sh
  ci/run_tests.sh
  ci/upgrade-aro-cluster.sh
  ci/upgrade_events.sh
  scripts/README.md
  scripts/metrics-sync.sh
Labels: approved, lgtm

#2702 misc: resolve various linting issues
  .golang-ci.yml
  cmd/osde2e/alert/cmd.go
  cmd/osde2e/cleanup/cmd.go
  cmd/osde2e/healthcheck/cmd.go
  cmd/osde2e/query/cmd.go
  cmd/osde2e/test/cmd.go
  pkg/common/aws/ec2.go
  pkg/common/aws/s3.go
  pkg/common/cluster/clusterutil.go
  pkg/common/concurrentviper/gen/main.go
  pkg/common/config/aws_config.go
  pkg/common/config/config.go
  pkg/common/config/gcp_config.go
  pkg/common/config/log_metrics.go
  pkg/common/helper/crud.go
  pkg/common/helper/helper.go
  pkg/common/helper/impersonate.go
  pkg/common/load/load.go
  pkg/common/metadata/metadata.go
  pkg/common/providers/mock/mock_test.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
  pkg/common/providers/rosaprovider/config.go
  pkg/common/runner/pod.go
  pkg/common/runner/results.go
  pkg/common/runner/results_test.go
  pkg/common/runner/runner.go
  pkg/common/runner/runner_test.go
  pkg/common/runner/service_test.go
  pkg/common/upgrade/managed.go
  pkg/common/upgrade/upgrade.go
  pkg/common/util/util.go
  pkg/e2e/e2e.go
  pkg/e2e/e2e_test.go
  pkg/e2e/metrics.go
  pkg/e2e/metrics_test.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/osd/inhibitions.go
  pkg/e2e/osd/ocm.go
  pkg/e2e/osd/rebalance_infra_nodes.go
  pkg/e2e/routemonitors/routemonitors.go
  pkg/e2e/state/prometheus.go
  pkg/e2e/verify/encrypted_storage.go
  pkg/e2e/verify/fips.go
  pkg/e2e/verify/sccs.go
  pkg/e2e/verify/storage.go
  pkg/metrics/client.go
  pkg/reporting/config.go
  pkg/reporting/reporters/weather/config.go
  pkg/reporting/reporters/weather/weather_reporter.go
  pkg/reporting/templates/list_templates.go
Labels: approved, lgtm

#2687 [OSD-25354] Enable job triggger for sdn to ovn migration in Jenkins
  test/sdn_migration/Dockerfile
  test/sdn_migration/Makefile
  test/sdn_migration/scripts/validate-sdn-ovn-migration-jobs.sh
  test/sdn_migration/sdn_migration_suite_test.go
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2716 Update Container Image
  test/sdn_migration/scripts/validate-sdn-ovn-migration-jobs.sh
Labels: approved, lgtm
