Repository openshift/osde2e, pull requests merged in 2024-04, with the labels that each got.

#2403 sdcicd-1255 add new instance types in MHC
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#2405 SDCICD-1260 remove workload ocp test from e2e-suite
  configs/e2e-suite.yaml
Labels: approved, lgtm

#2406 SDCICD-1184: remove initially migrated tests
  cmd/osde2e/test/cmd.go
  go.mod
  go.sum
  pkg/common/label/label.go
  pkg/e2e/operators/customdomains.go
  pkg/e2e/operators/managedupgrade.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/mustgather.go
  pkg/e2e/operators/ocmagent/ocmagent.go
  pkg/e2e/operators/operators.go
  pkg/e2e/operators/osdmetricsexporter.go
  pkg/e2e/operators/rbac.go
  pkg/e2e/operators/splunkforwarder.go
Labels: approved, lgtm, jira/valid-reference

#2410 SDCICD-1198 make conformance test command runner compatible with GCP
  pkg/e2e/openshift/config.go
Labels: approved, lgtm

#2413 cmd/osde2e: error strings should not be capitalized (ST1005)
  cmd/osde2e/cleanup/cmd.go
  cmd/osde2e/completion/cmd.go
Labels: approved, lgtm

#2414 misc: should omit comparison to bool constant
  pkg/common/providers/ocmprovider/cluster.go
  pkg/e2e/operators/cloudingress/certificate.go
  pkg/e2e/operators/cloudingress/dnsname.go
  pkg/e2e/operators/cloudingress/public_private.go
  pkg/e2e/operators/cloudingress/rhapi_lb.go
  pkg/e2e/operators/cloudingress/routeSelector.go
Labels: approved, lgtm

#2412 rosaprovider: klogr -> textlogger
  pkg/common/providers/rosaprovider/rosa.go
Labels: approved, lgtm

#2411 pkg/common/cluster: deprecated wait.PollImmediate
  pkg/common/cluster/clusterutil.go
Labels: approved, lgtm

#2422 do not fail test for errors coming from metrics bucket
  pkg/common/aws/s3.go
  pkg/common/helper/runner.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2425 sdcicd-1274 remove references to abandoned metrics s3 bucket
  pkg/common/aws/s3_session.go
  pkg/common/aws/s3_test.go
  pkg/common/config/config.go
  pkg/common/helper/runner.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/e2e/e2e.go
  pkg/reporting/generate_report.go
Labels: approved, lgtm

#2427 SDCICD-1266: resolve lint issues in pkg/reporting
  pkg/reporting/generate_report.go
  pkg/reporting/report_to_slack.go
  pkg/reporting/reporters/weather/weather_reporter.go
Labels: approved, lgtm, jira/valid-reference

#2423 SDCICD-1198 provide required gcp args to ocp tests
  pkg/e2e/openshift/config.go
Labels: approved, lgtm, tide/merge-method-squash

#2424 Add cleanup of all old clusters
  cmd/osde2e/cleanup/cmd.go
Labels: approved, lgtm

#2429 SDCICD-1240 skip waiting if cluster already uninstalling
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#2430 Update cleanup stage cluster log
  cmd/osde2e/cleanup/cmd.go
Labels: approved, lgtm

#2426 misc: bump go 1.21
  Dockerfile.osde2e
  go.mod
  go.sum
Labels: approved, lgtm

#2434 SDCICD-1255 updating instance type list to match MCC
  pkg/e2e/osd/machinehealthcheck.go
Labels: approved, lgtm

#2428 SDCICD-1266: duplicate import - pkg/common/cluster
  pkg/e2e/e2e.go
Labels: approved, lgtm, jira/valid-reference

#2437 SDCICD-1266: PollImmediate -> PollUntilContextTimeout
  pkg/common/helper/crud.go
  pkg/common/helper/helper.go
  pkg/common/helper/projects.go
  pkg/common/helper/utilities.go
  pkg/common/helper/workloads.go
Labels: approved, lgtm, jira/valid-reference

#2435 SDCICD-1266 deprecate more instances of pollImmediate
  pkg/common/runner/pod.go
  pkg/common/runner/service.go
Labels: approved, lgtm

#2436 SDCICD-1266: replace deprecated Int*Ptr func
  pkg/common/runner/pod.go
Labels: approved, lgtm, jira/valid-reference

#2439 SDCICD-1266: switch kms import out
  go.mod
  pkg/e2e/verify/encrypted_storage.go
Labels: approved, lgtm, jira/valid-reference

#2438 SDCICD-1266: pass context down through the runner
  pkg/common/runner/pod.go
  pkg/common/runner/results_test.go
  pkg/common/runner/runner.go
  pkg/common/runner/service.go
  pkg/common/runner/service_test.go
Labels: approved, lgtm, jira/valid-reference

#2440 SDCICD-1266: resolve all error strings capitalized
  pkg/common/cluster/clusterutil.go
  pkg/common/cluster/healthchecks/healthcheckjob.go
  pkg/common/cluster/healthchecks/machines.go
  pkg/common/helper/olm.go
  pkg/common/helper/workloads.go
  pkg/common/prometheus/connect.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/quota.go
  pkg/common/runner/results.go
  pkg/common/upgrade/upgrade.go
  pkg/common/versions/upgradeselectors/latest_version_selector.go
  pkg/common/versions/upgradeselectors/latest_y_selector.go
  pkg/common/versions/upgradeselectors/latest_z_selector.go
  pkg/debug/diff.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm, jira/valid-reference

#2441 SDCICD-1266: resolve unnecessary actions lint
  pkg/common/metadata/metadata.go
  pkg/common/upgrade/managed.go
  pkg/e2e/e2e.go
  pkg/e2e/harness_runner/harness_runner.go
  pkg/e2e/osd/dedicatedadmin.go
Labels: approved, lgtm, jira/valid-reference

#2442 SDCICD-1271 add elasticIP release process to cleanup command
  cmd/osde2e/cleanup/cmd.go
  pkg/common/aws/ec2.go
Labels: approved, lgtm

#2450 SDCICD-1271 update log for skipping deletion of associated ips
  pkg/common/aws/ec2.go
Labels: approved, lgtm

#2451 SDCICD-1198 ocp test skip regex
  cmd/osde2e/test/cmd.go
  pkg/common/config/config.go
  pkg/e2e/openshift/config.go
Labels: approved, lgtm
