Repository openshift/osde2e, pull requests merged in 2024-11, with the labels that each got.

#2757 .tekton/*: add required rpms-signature-scan task
  .tekton/fedramp-pull-request.yaml
  .tekton/fedramp-push.yaml
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
  .tekton/sdn-migration-pull-request.yaml
  .tekton/sdn-migration-push.yaml
Labels: approved

#2759 .tekton/osde2e-main*: fix results ref
  .tekton/fedramp-pull-request.yaml
  .tekton/fedramp-push.yaml
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
  .tekton/sdn-migration-pull-request.yaml
  .tekton/sdn-migration-push.yaml
Labels: approved

#2770 test/sdn_migration: resolve lint issues
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm

#2769 e2e: remove moved operator tests
  cmd/osde2e/test/cmd.go
  pkg/e2e/operators/certman.go
  pkg/e2e/operators/configurealertmanager/configurealertmanager.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#2773 SDCICD-1411 add ability to alternate between two aws accounts
  pkg/common/config/aws_config.go
  pkg/common/config/config.go
Labels: approved, lgtm

#2775 update osde2e-common from 9d3f9c8bf1f4 to 751c51bf8518
  go.mod
  go.sum
  pkg/common/cluster/healthchecks/healthcheckjob.go
  pkg/e2e/openshift/osdclusterready.go
  test/mcscupgrade/mcscupgrade_test.go
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm

#2774 Add ClusterOperator health check
  test/sdn_migration/sdn_migration_test.go
Labels: approved, lgtm, tide/merge-method-squash
