Repository openshift/osde2e, pull requests merged in 2024-06, with the labels that each got.

#2508 e2e/state: use helper client
  pkg/e2e/state/alerts.go
Labels: approved, lgtm

#2515 give cloud provider id env var to harness images
  pkg/common/helper/helper.go
Labels: approved, lgtm

#2518 .tekton: set build-source-image true
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
Labels: approved, lgtm

#2516 sdcicd-1198 improve gcp configs to properly set ccs creds
  pkg/common/config/config.go
  pkg/common/config/gcp_config.go
  pkg/common/helper/helper.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/ocmprovider/config.go
  pkg/e2e/openshift/config.go
Labels: approved, lgtm

#2520 skip encrypted cloud storage access test for GCP non-CCS
  pkg/e2e/verify/encrypted_storage.go
Labels: approved, lgtm

#2521 add cloud secrets to harness passthough
  pkg/common/helper/helper.go
  pkg/common/load/load.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2531 remove clean-up-rosa.sh
  scripts/clean-up-rosa.sh
Labels: approved, lgtm, ok-to-test

#2536 Enable OSDe2e to create rosa MintMode Clusters for testing
  configs/mintMode.yaml
  go.mod
  go.sum
  pkg/common/providers/rosaprovider/cluster.go
  pkg/common/providers/rosaprovider/config.go
Labels: approved, lgtm

#2537 Enable MINT_MODE for parameterized-job
  scripts/parameterized-job.sh
Labels: approved, lgtm

#2534 SDCICD-1306: add tekton pipeline to execute osde2e
  .tekton/osde2e-main-e2e-test.yaml
Labels: approved, lgtm, jira/valid-reference

#2535 Update date format for cleanup cluster logs
  cmd/osde2e/cleanup/cmd.go
Labels: approved, lgtm

#2532 SDCICD-1306: write std konflux TEST_OUTPUT results
  pkg/common/config/config.go
  pkg/e2e/e2e.go
Labels: approved, lgtm, jira/valid-reference

#2541 SDCICD-1306: add new EC compatible Dockerfile
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
  osde2e.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2544 e2e/webhooks: use dynamic client
  go.mod
  go.sum
  pkg/common/helper/impersonate.go
  pkg/e2e/webhooks/webhooks.go
Labels: approved, lgtm

#2533 e2e: skip setup if cluster-id provided
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2546 misc: drop all cluster scaling code
  pkg/common/cluster/clusterutil.go
  pkg/common/config/config.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
Labels: approved, lgtm

#2556 do not delete harness logs bucket in s3 cleanup
  pkg/common/aws/s3.go
Labels: approved, lgtm

#2555 pkg/common/helper: delete unused crud helpers
  go.mod
  go.sum
  pkg/common/helper/crud.go
Labels: approved, lgtm

#2559 SDCICD-1306: only build on specific files
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2560 SDCICD-1306: set pr-check config/skip must-gather
  .tekton/osde2e-main-e2e-test.yaml
Labels: approved, lgtm, jira/valid-reference

#2558 SDCICD-1306: use els base image
  osde2e.Dockerfile
Labels: approved, jira/valid-reference

#2562 e2e/operators: delete dvo tests
  pkg/e2e/operators/dvo.go
  pkg/e2e/operators/operators.go
Labels: approved, lgtm

#2565 SDCICD-1306: copy license and set USER
  osde2e.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2571 Delete config file for complete-e2e
  configs/complete-e2e.yaml
Labels: approved, lgtm

#2573 SDCICD-1252 remove expiration date setting from prod clusters
  pkg/common/providers/ocmprovider/cluster.go
Labels: approved, lgtm

#2577 sdcicd-885 add missing cloud provider region var to harness image
  pkg/common/helper/helper.go
Labels: approved, lgtm
