Repository openshift/osde2e, pull requests merged in 2025-04, with the labels that each got.

#2910 misc: drop alert pkg/cmd
  .tekton/fedramp-pull-request.yaml
  .tekton/fedramp-push.yaml
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
  .tekton/sdn-migration-pull-request.yaml
  .tekton/sdn-migration-push.yaml
  cmd/osde2e/alert/cmd.go
  cmd/osde2e/main.go
  pkg/common/alert/alert.go
  pkg/e2e/openshift/app_builds.go
  pkg/e2e/openshift/disruptive.go
  pkg/e2e/openshift/hypershift/verifyInstall.go
  pkg/e2e/openshift/images.go
  pkg/e2e/operators/managedvelero.go
  pkg/e2e/operators/prunejob.go
  pkg/e2e/osd/daemonsets.go
  pkg/e2e/osd/dedicatedadmin.go
  pkg/e2e/osd/inhibitions.go
  pkg/e2e/osd/machinehealthcheck.go
  pkg/e2e/osd/nodelabels.go
  pkg/e2e/osd/ocm.go
  pkg/e2e/osd/olm.go
  pkg/e2e/osd/privileged.go
  pkg/e2e/osd/rebalance_infra_nodes.go
  pkg/e2e/proxy/postinstall.go
  pkg/e2e/state/alerts.go
  pkg/e2e/verify/encrypted_storage.go
  pkg/e2e/verify/fips.go
  pkg/e2e/verify/imagestreams.go
  pkg/e2e/verify/loadbalancers.go
  pkg/e2e/verify/pods.go
  pkg/e2e/verify/routes.go
  pkg/e2e/verify/sccs.go
  pkg/e2e/verify/storage.go
  pkg/e2e/verify/user_workload_monitoring.go
  pkg/e2e/workloads/workloads.go
Labels: approved, lgtm

#2912 misc: drop query and report cmd
  Makefile
  cmd/osde2e/main.go
  cmd/osde2e/query/cmd.go
  cmd/osde2e/report/cmd.go
  go.mod
  go.sum
  pkg/common/cluster/clusterutil.go
  pkg/common/cluster/healthchecks/certs.go
  pkg/common/cluster/healthchecks/clusterversionoperator.go
  pkg/common/cluster/healthchecks/machines.go
  pkg/common/cluster/healthchecks/nodes.go
  pkg/common/cluster/healthchecks/operators.go
  pkg/common/metadata/addon.go
  pkg/common/metadata/metadata.go
  pkg/common/metadata/metadata_test.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/spi/cluster.go
  pkg/common/upgrade/upgrade.go
  pkg/common/versions/versionselector.go
  pkg/e2e/e2e.go
  pkg/e2e/metrics.go
  pkg/e2e/metrics_test.go
  pkg/e2e/routemonitors/routemonitors.go
  pkg/metrics/addon_metadata.go
  pkg/metrics/addon_metadata_test.go
  pkg/metrics/client.go
  pkg/metrics/client_test.go
  pkg/metrics/events.go
  pkg/metrics/events_test.go
  pkg/metrics/junitresult.go
  pkg/metrics/junitresult_test.go
  pkg/metrics/metadata.go
  pkg/metrics/metadata_test.go
  pkg/metrics/objects.go
  pkg/metrics/objects_test.go
  pkg/reporting/config.go
  pkg/reporting/generate_report.go
  pkg/reporting/local_output.go
  pkg/reporting/report_to_slack.go
  pkg/reporting/reporters/getreporter.go
  pkg/reporting/reporters/reporters_generated.go
  pkg/reporting/reporters/weather/config.go
  pkg/reporting/reporters/weather/weather_reporter.go
  pkg/reporting/spi/registry.go
  pkg/reporting/spi/reporter_spi.go
  pkg/reporting/templates/list_templates.go
  pkg/reporting/templates/template_cache.go
  pkg/reporting/templates/write_report.go
  scripts/generate-reporters-import.sh
Labels: approved, lgtm

#2911 SDCICD-1521: only healthcheck nodes
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
  cmd/osde2e/test/cmd.go
  docs/Config.md
  go.mod
  go.sum
  pkg/common/cluster/clusterutil.go
  pkg/common/cluster/healthchecks/nodes.go
  pkg/common/config/config.go
  pkg/common/providers/rosaprovider/cluster.go
  pkg/e2e/e2e.go
Labels: approved, lgtm, jira/valid-reference

#2917 pkg/common: rm external prom and db config
  pkg/common/config/config.go
  pkg/common/prometheus/connect.go
Labels: approved, lgtm

#2919 misc: drop events,metrics,routemonitors
  ci/acceptance-tests-template.yaml
  cmd/osde2e/arguments/arguments.go
  cmd/osde2e/main.go
  cmd/osde2e/update/flag.go
  docs/Config.md
  go.mod
  go.sum
  pkg/common/config/config.go
  pkg/common/config/log_metrics.go
  pkg/common/config/log_metrics_test.go
  pkg/common/events/event_type.go
  pkg/common/events/events.go
  pkg/common/events/events_test.go
  pkg/common/helper/helper.go
  pkg/e2e/e2e.go
  pkg/e2e/e2e_test.go
  pkg/e2e/routemonitors/routemonitors.go
  scripts/trigger-jobs.py
Labels: approved, lgtm

#2922 Feat(SDE-4821): add cad e2e
  configs/e2e-suite.yaml
Labels: approved, lgtm

#2898 misc: upgrade to golangci-lint v2
  .golang-ci.yml
  Makefile
Labels: approved, lgtm

#2929 .tekton/osde2e*: migrate to oci-ta
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
Labels: approved, lgtm

#2928 set operator e2e timeout default to 900s
  configs/test-harness.yaml
Labels: approved, tide/merge-method-squash

#2931 Remove cluster hibernate and resume references from osde2e
  pkg/common/cluster/clusterutil.go
  pkg/common/config/config.go
  pkg/common/providers/mock/mock.go
  pkg/common/providers/ocmprovider/cluster.go
  pkg/common/providers/rosaprovider/wrapped_calls.go
  pkg/common/spi/provider.go
  pkg/e2e/e2e.go
Labels: approved, lgtm

#2932 .tekton/*: migrate to bundle ref pipeline
  .tekton/fedramp-pull-request.yaml
  .tekton/fedramp-push.yaml
  .tekton/sdn-migration-pull-request.yaml
  .tekton/sdn-migration-push.yaml
Labels: approved, lgtm

#2933 misc: update renovate config to group packages
  renovate.json
Labels: approved, lgtm

#2934 .tekton/osde2e*: skip running on renovate config changes
  .tekton/osde2e-main-pull-request.yaml
  .tekton/osde2e-main-push.yaml
Labels: approved, lgtm
